project:
  type: book
  output-dir: "docs"

lang: es

book:
  title: "Bitácoras Grupo #4, CA-204 (II-2024)"
  author: "Debbie Con, Andrey Prado, Aarón Retana"
  date: today
  search: true
  repo-url: https://github.com/DebbieCon/Bitacoras-Grupo-4-CA-0204-II-2024-.git
 #site-url: # Vacío por el momento
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:
    - "index.qmd"
    - "bitacora-1.qmd"
    - "references.bib"

bibliography: references.bib

format:
  html:
      # Pueden usar cualquier tema de los que están aca:
      # https://quarto.org/docs/output-formats/html-themes.html a excepción de
      # los oscuros porque no entiende nada.
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto
  cache: true

from: markdown+tex_math_single_backslash+emoji
link-external-newwindow: true