---
editor: 
  markdown: 
    wrap: 72
---

# Bitácora 2: Planificación y Análisis


## Parte de planificación

### Ordenamiento de la literatura


| Organización |                                                                                                                                                                               |                                                                                                                   | Literatura                                                                                                                                          |      |                                                                                |
|--------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------|------|--------------------------------------------------------------------------------|
| Tipo         | Tema General                                                                                                                                                                  | Tema especifico                                                                                                   | Título                                                                                                                                              | Año  | Autor(es)                                                                      |
| Temático     | Factores que afectan el desempeño académico de los estudiantes de nivel superior.                                                                                             | Técnicas de recolección y análisis cuantitativo.                                                                  | Factores asociados al rendimiento académico en estudiantes universitarios desde el nivel socioeconómico: Un estudio en la Universidad de Costa Rica | 2013 | Guiselle María Garbanzo Vargas                                                 |
| Temático     | Factores que afectan el desempeño académico de los estudiantes de nivel superior.                                                                                             | Estudio cuantitativo de encuesta elaborada a partir del material bibliográfico.                                   | Factores que afectan el desempeño académico de los estudiantes de nivel superior en Rioverde, San Luis Potosí, México                               | 2011 | Juan Manuel Izar Landeta; Carmen Berenice Ynzunza Cortés; Héctor López Gama    |
| Temático     | Factores que afectan el desempeño académico de los estudiantes de nivel superior                                                                                              | Relación entre el desempeño académico y factores institucionales, pedagógicos, psicosociales y sociodemográficos. |                                                                                                                                                     | 2007 | Montero Rojas, Eiliana; Villalobos Palma, Jeannette; Valverde Bermúdez, Astrid |
| Teórico      | El factor económico como principal causa del abandono de los estudios en Centroamérica y su impacto en la sociedad.                                                           | Deserción estudiantil en la educación superior en centroamérica a causa de factores económicos                    | El factor económico como principal causa de deserción estudiantil universitaria en Centroamérica                                                    | 2022 | Marlon Lobos y Judith Rodriguez                                                |
| Teórico      | Deserción escolar en jóvenes mujeres y sus factores asociados.                                                                                                                | Deserción escolar y vulnerabilidad juvenil.                                                                       | Los jóvenes que desertan de la educación media: virajes y puntos de no retorno.                                                                     | 2015 | Marcos Jacobo Estrada-Ruiz.                                                    |
| Teórico      | Análisis de las teoría de los sistemas ecológicos de Urie Bronfenbrenner para entender la deserción universitaria con el fin de identificar y prevenir los factores de riesgo | Deserción universitaria y su análisis a través de la teoría de los Sistema Ecológicos                             | La teoría de los sistemas ecológicos de Urie Bronfenbrenner como marco para comprender la deserción universitaria                                   | 2023 | Barraza Niebles                                                                |
| Teórico      | Análisis del fenómenos de fracaso escolar en la educación secundaria, identificando factores que afectan el rendimiento académico y proponiendo estrategias para su mejoría   | Teoría del fracaso escolar y sus condicionantes en la educación secundaria                                        | Diversos condicionantes del fracaso escolar en la educación secundaria                                                                              | 2009 | Valentin Martinez-Otero Perez                                                  |
| Teórico      | Modelos Multinivel                                                                                                                                                            | Análisis de Datos                                                                                                 | Los modelos multinivel como herramienta para la investigación educativa                                                                             | 2008 | Javier Murillo Torrecilla                                                      |
| Metodológico | Base de datos de universidades Europeas para identificar los posibles factores que afectan en la decisión de deserción escolar.                                               | Análisis de Datos y Aprendizaje Automático                                                                        | Predicting Student Dropout and Academic Success                                                                                                     | 2022 | Valemtin Realinho, Jorge Machado, Luis Baptista, Mónica V. Martins             |
| Metodológico | Impacto del uso de tecnologías de la información y la comunicación en el rendimiento académico de estudiantes universitarios                                                  | Impacto positivo del uso de la tecnología sobre el rendimiento académico a nivel universitario.                   | Análisis cuantitativo de las variables que influyen en el rendimiento universitario.                                                                | 2018 | Martha Jiménez García                                                          |

## Enlaces de la literatura

### Resumen de las fichas literarias

El artículo comienza con observaciones sobre el rendimiento académico
como indicador de la calidad de la educación y define de manera general
algunos componentes teóricos relevantes: rendimiento académico, nivel
socioeconómico y la relación entre ambos. Luego, se plantea una encuesta
que contempla: sexo, edad, beca, colegio de procedencia, satisfacción
con la carrera, hábitos de estudio, nivel socioeconómico, satisfacción
con los profesores, convivencia familiar, nivel educativo de los padres,
nota de admisión, entre otros. La encuesta fue aplicada a 120
estudiantes y esta muestra fue separada en dos subgrupos según la
demanda (alta o baja) de la carrera escogida para elaborar por separado
modelos de regresión lineal múltiple. Dentro de cada subgrupo, se
distinguió entre aquellos estudiantes con la máxima categoría de beca y
aquellos que no solicitaron beca. Finalmente, se concluye que en las
carreras de alta demanda, las principales diferencias entre becados y no
becados ocurrieron en las variables de satisfacción universitaria,
hábitos de estudio, satisfacción con los profesores y nivel
socioeconómico; pero estas no producen mayor efecto sobre el promedio de
calificación. Por otro lado, en las carreras de baja demanda, las
variables de nota de admisión, satisfacción con los servicios y nivel
socioeconómico, sí tuvieron un impacto más marcado sobre las diferencias
en el promedio entre becados y no becados. 

El artículo comienza con una breve descripción del contexto social y
geográfico en el que se desarrolla el estudio (Rioverde, México).
Seguidamente, se revisaron fuentes bibliográficas con objetivos
similares para identificar los factores más relevantes en el desempeño
académico. Las fuentes consultadas proponen diferentes enfoques, por
ejemplo: factores fisiológicos, pedagógicos, psicológicos, sociológicos,
familiares, institucionales, entre otros. A partir de esto, se aplicó
una encuesta a estudiantes, la cual recopila información sobre edad,
género, nivel socioeconómico, orientación vocacional, calificaciones
promedio y aspiraciones futuras. Con los resultados determinaron algunas
características generales sobre la muestra estudiada y se generó un
modelo de regresión lineal con la calificación promedio como variable
dependiente y los 10 aspectos contemplados dentro de “aspiraciones
futuras” como variables independientes. También se efectuó un análisis
de varianza entre el promedio de carrera, la orientación vocacional, el
nivel socioeconómico, escolaridad de los padres y el género. Se concluye
que las variables con una mayor correlación al promedio fueron el género
y la intención de estudiar un posgrado, mientras que el la orientación
vocacional, el nivel socioeconómico y escolaridad de los padres no
mostraron mayor impacto.  

El artículo busca estudiar la relación entre el rendimiento académico y
los factores institucionales, pedagógicos, psicosociales y
sociodemográficos en estudiantes universitarios. Primero, se definen
conceptos relevantes como el rendimiento académico, y se delimitan los
factores del estudio, basándose en la literatura existente. A partir de
esto, se elaboraron dos encuestas: una se aplicó a estudiantes y abarca
elementos como edad, nivel socioeconómico, situación laboral,
inteligencia emocional, asistencia a cursos, satisfacción con la
carrera, entre otros; la otra encuesta estaba dirigida a los profesores
y contempla variables como grado, años de experiencia, número de
estudiantes, métodos de enseñanza, formas de evaluación, etc. Los
resultados fueron analizados mediante un modelo de niveles múltiples.
Algunos de los hallazgos del estudio son: el índice inteligencia
emocional y el promedio de admisión tienen relación positiva con el
desempeño, mientras que la evaluación centrada en exámenes y la
enseñanza enfocada en clases magistrales tuvieron efectos negativos en
el desempeño. 

El artículo se propone demostrar que los factores económicos son los más
influyentes en la deserción estudiantil a nivel universitario en
Centroamérica. Basado en estudios independientes en Guatemala, Honduras,
El Salvador, Nicaragua y Costa Rica, el autor argumenta que los altos
costos de matrícula, materiales, transporte, alimentación y demás gastos
son el principal obstáculo que enfrentan los estudiantes para continuar
con su carrera, así como lo es la imposibilidad de estudiar y trabajar
simultáneamente. Sin embargo, se destacan otros factores que no son de
carácter económico, como la personalidad del estudiante, que incluye
aspectos como tolerancia a la frustración y autoestima. Asimismo, se
determina que los antecedentes familiares en educación son relevantes
para el estudiante. Por otro lado, se establece que el factor académico
o institucional, que incluye aspectos como horarios de clase,
metodología de enseñanza y personal docente, también juegan un papel en
la trayectoria académica del estudiante. Finalmente, el artículo
concluye que es fundamental abordar estos desafíos para mejorar la
retención estudiantil y fomentar el acceso a la educación superior en
Centroamérica. 

Este documento explora las experiencias de jóvenes mujeres que desertan
de la educación media en Hermosillo, Sonora. A través de entrevistas
biográficas, se identifican los factores que contribuyen a la deserción,
como la presión social, las responsabilidades familiares y la falta de
apoyo institucional. El estudio revela que muchas de estas jóvenes
enfrentan vulnerabilidades significativas tras abandonar la escuela, lo
que impacta sus trayectorias de vida. Además, se destaca la importancia
de las relaciones familiares y el contexto social en la decisión de
regresar a la educación. La investigación subraya la necesidad de
abordar las desigualdades de género en el ámbito educativo.\

En los últimos años se ha dado una creciente preocupación por la
deserción universitaria en Colombia, dado que alrededor de solo los
estudiantes que inician la educación superior logran graduarse. Usando
la Teoría de los Sistemas Ecológicos de Bronfenbrenner se examinan los
factores que contribuyen a este fenómeno. Entre los factores
investigados se encuentran: los problemas económicos, falta de apoyo
social y la deficiencia de las políticas educativas. Sin embargo, esta
teoría no brinda apoyo para entender los aspectos más sociales y
culturales, sólo los factores más inmediatos. Se destaca la importancia
de un enfoque más integral que reconozca la complejidad del fenómeno por
la interconexión de los distintos factores para poder crear reformas y
desarrollar estrategias para prevenir el abandono escolar.  

El texto aborda el tema del fracaso escolar en la educación secundaria.
Se enfoca en la interacción de factores tanto individuales como
contextuales que podrían afectar el rendimiento de un estudiante. El
autor reúne información en base a investigaciones previas y reflexiones
teóricas e identifica condicionantes como el contexto socioeconómico,
las metodologías de enseñanza y la inteligencia emocional del estudiante
como parte de los determinantes del rendimiento académico. Se realiza
una crítica acerca de la visión tradicional de la inteligencia y el
enfoque mecanicista de la educación. Se sugiere que se consideren más
aspectos emocionales, morales y sociales. Las normas y herramientas
actuales que buscan solventar este problema , no son suficientes por lo
que se pide una revisión de los mismos. Sin embargo, desde una
perspectiva más integral donde se combine la mejor atención a las
necesidades individuales del estudiante como a la calidad de la
educación recibida.  El artículo comienza presentando una herramienta
crucial para el análisis de datos los cuales siguen una jerarquía,
presenta los modelos multinivel como una herramienta metodológica para
la investigación educativa. Luego presenta las limitaciones que
presentan los modelos tradicionales de regresión lineal y argumenta que
para cierto tipo de variables es más eficaz el modelo multinivel. El
autor también proporciona un resultado importante del análisis de datos
por esta metodología y es que este modelo permite separar resultados
según el nivel, por ejemplo presenta el resultado de la varianza y
covarianza entre niveles, así se consigue un entendimiento más profundo
del tema.\

El artículo proporciona una base de datos de distintas universidades
europeas con datos demográficos, familiares, socioeconómicos,
macroeconómicos de los estudiantes matriculados y que al cabo de un año
de clases abandonaron o se mantuvieron en la universidad. Muestra un
total de 4424 registros. Los autores emplean modelos de análisis de
datos y aprendizaje automático para intentar predecir el éxito o
deserción escolar. Presentan distintas dificultades al ordenar los
factores en su importancia al relacionarse con el resultado esperado
pero lograron concluir que efectivamente estas variables están
relacionadas.\

Basándose en literatura sobre la importancia de implementar la
tecnología en el proceso de enseñanza-aprendizaje, esta investigación se
propone analizar el impacto del uso de diferentes herramientas digitales
sobre el rendimiento académico en una universidad pública mexicana. Se
aplicó una encuesta en la que se les pedía a los estudiantes indicar con
qué frecuencia utilizan ciertas herramientas en una semana. Las
variables contempladas para cada estudiante fueron el rendimiento
académico, el género, la beca, el semestre, las materias reprobadas y la
frecuencia de uso de seis herramientas digitales (cada una por
separado). A partir de los datos recolectados, se elaboró un modelo,
cuyos resultados permiten afirmar que el rendimiento académico aumenta
cuando hay cambios en alguna variable independiente y las demás se
mantienen constantes. Se concluye que la beca y el uso de herramientas
digitales contribuyen a un mejor rendimiento académico, pero se advierte
que la implementación de estas tecnologías en el aula debe ser bien
planificada.\

### Resumen, contraste  Contribución propia 

***Factores asociados al rendimiento académico en estudiantes universitarios desde el nivel socioeconómico: Un estudio en la Universidad de Costa Rica***\
*Resumen:* El artículo de Garbanzo Vargas (2013) comienza con observaciones sobre el rendimiento académico como indicador de la calidad de la educación y define de manera general algunos componentes teóricos relevantes: rendimiento académico, nivel socioeconómico y la relación entre ambos. Luego, plantea una encuesta que contempla: sexo, edad, beca, colegio de procedencia, satisfacción con la carrera, hábitos de estudio, nivel socioeconómico, satisfacción con los profesores, convivencia familiar, nivel educativo de los padres, nota de admisión, entre otros. La encuesta fue aplicada a 120 estudiantes y esta muestra fue separada en dos subgrupos según la demanda (alta o baja) de la carrera escogida para elaborar por separado modelos de regresión lineal múltiple. Dentro de cada subgrupo, se distinguió entre aquellos estudiantes con la máxima categoría de beca y aquellos que no solicitaron beca. Finalmente, concluyó que en las carreras de alta demanda, las principales diferencias entre becados y no becados ocurrieron en las variables de satisfacción universitaria, hábitos de estudio, satisfacción con los profesores y nivel socioeconómico; pero estas no producen mayor efecto sobre el promedio de calificación. Por otro lado, en las carreras de baja demanda, las variables de nota de admisión, satisfacción con los servicios y nivel socioeconómico, sí tuvieron un impacto más marcado sobre las diferencias en el promedio entre becados y no becados. \
*Contraste:* Un elemento distintivo de esta fuente es la marcada separación que hace entre carreras de alta y baja demanda, así como entre estudiantes becados y no becados, al estudiar los factores que pueden afectar el rendimiento académico. Este es un enfoque metodológico que no está presente en otros estudios similares como Izar Landeta, Ynzunza Cortés y López Gama (2011) y Montero Rojas, Villalobos Palma, y Valverde Bermúdez (2007), por lo que no es imprudente asumir que estos autores no consideran que estos factores sean tan significativos. \
*Contribución:* En general, esta es una fuente valiosa porque muestra el manejo de una cantidad de variables similar a las que se consideran en este trabajo, pero el artículo en sí parece decir más sobre las diferencias entre los perfiles de los estudiantes becados y no becados que acerca de los factores que afectan el rendimiento académico, a pesar de que ese fuera su objetivo inicial. \\


***Factores que afectan el desempeño académico de los estudiantes de nivel superior en Rioverde, San Luis Potosí, México***\
*Resumen:* Izar Landeta, Ynzunza Cortés y López Gama (2011) inician su artículo con una breve descripción del contexto social y geográfico en el que se desarrolla el estudio (Rioverde, México). Seguidamente, revisaron fuentes bibliográficas con objetivos similares para identificar los factores más relevantes en el desempeño académico. Las fuentes consultadas proponen diferentes enfoques, por ejemplo: factores fisiológicos, pedagógicos, psicológicos, sociológicos, familiares, institucionales, entre otros. A partir de esto, aplicaron una encuesta a estudiantes, la cual recopila información sobre edad, género, nivel socioeconómico, orientación vocacional, calificaciones promedio y aspiraciones futuras. Con los resultados determinaron algunas características generales sobre la muestra estudiada y se generó un modelo de regresión lineal con la calificación promedio como variable dependiente y los 10 aspectos contemplados dentro de “aspiraciones futuras” como variables independientes. También realizaron un análisis de varianza entre el promedio de carrera, la orientación vocacional, el nivel socioeconómico, escolaridad de los padres y el género. Concluyeron que las variables con una mayor correlación al promedio fueron el género y la intención de estudiar un posgrado, mientras que el la orientación vocacional, el nivel socioeconómico y escolaridad de los padres no mostraron mayor impacto.\ 
*Contraste:* Esta fuente comparte una base teórica con Montero Rojas, Villalobos Palma, y Valverde Bermúdez (2007), pues ambos estudios consideran que los factores institucionales, pedagógicos y psicológicos son de particular importancia para el rendimiento académico, pero los resultados a los que llegan son distintos: uno concluye que el género y la aspiración a un posgrado son las variables de mayor peso, mientras que el otro se inclina por inteligencia emocional, promedio de admisión, métodos de enseñanza y formas de evaluación. \
*Contribución:* Esta fuente es de especial interés para esta investigación, ya que incluye algunos métodos de estadística descriptiva aplicados directamente al tema de estudio, como gráficos de distribución de tipo histograma sobre calificaciones promedio, por ejemplo. Esto muestra la viabilidad de extraer conclusiones de los datos sin necesariamente emplear técnicas estadísticas avanzadas. 


***Factores institucionales, pedagógicos, psicosociales y sociodemográficos asociados al rendimiento académico en la Universidad de Costa Rica: un análisis multinivel***\

*Resumen:* En su artículo, Montero Rojas, Villalobos Palma, y Valverde Bermúdez (2007) buscan estudiar la relación entre el rendimiento académico y los factores institucionales, pedagógicos, psicosociales y sociodemográficos en estudiantes universitarios. Primero, definen conceptos relevantes como el rendimiento académico, y delimitan los factores del estudio, basándose en la literatura existente. A partir de esto, elaboraron dos encuestas: una se aplicó a estudiantes y abarca elementos como edad, nivel socioeconómico, situación laboral, inteligencia emocional, asistencia a cursos, satisfacción con la carrera, entre otros; la otra encuesta estaba dirigida a los profesores y contempla variables como grado, años de experiencia, número de estudiantes, métodos de enseñanza, formas de evaluación, etc. Los resultados fueron analizados mediante un modelo de niveles múltiples. Algunos de los hallazgos del estudio son: el índice inteligencia emocional y el promedio de admisión tienen relación positiva con el desempeño, mientras que la evaluación centrada en exámenes y la enseñanza enfocada en clases magistrales tuvieron efectos negativos en el desempeño. \
*Contraste:*  Este artículo se distingue de otras fuentes por su énfasis en el papel del docente en el desempeño académico del estudiante. En cambio, Garbanzo Vargas (2013), prioriza el ámbito familiar del estudiante y, aunque incluye la satisfacción con el docente dentro de las variables observadas, lo hacen desde la opinión del estudiante, mientras que Montero Rojas, Villalobos Palma, y Valverde Bermúdez (2007) desarrollan una encuesta separada para aplicarla a los docentes y estudiar el fenómeno desde la perspectiva del profesor. Este enfoque metodológico les permitió encontrar resultados sobre el rol del docente que no están presentes en las demás fuentes consultadas. \
*Contribución:* Un aspecto interesante de esta fuente es que algunos de los resultados obtenidos parecen contradecir ciertas teorías generalmente aceptadas en la bibliografía sobre la que se basa el propio estudio, a pesar de que este estuviera diseñado para contemplar todas las variables que se consideraron pertinentes, esto es importante para la investigación porque advierte sobre la variabilidad de cada base de datos y la posibilidad de que existan otras tendencias que no se puedan explicar a través de los métodos escogidos. 

***El factor económico como principal causa de deserción estudiantil universitaria en Centroamérica***\
*Resumen:* El artículo de Marlon Lobos y Judith Rodriguez (2022) se propone demostrar que los factores económicos son los más influyentes en la deserción estudiantil a nivel universitario en Centroamérica. Basado en estudios independientes en Guatemala, Honduras, El Salvador, Nicaragua y Costa Rica, el autor argumenta que los altos costos de matrícula, materiales, transporte, alimentación y demás gastos son el principal obstáculo que enfrentan los estudiantes para continuar con su carrera, así como lo es la imposibilidad de estudiar y trabajar simultáneamente. Sin embargo, se destacan otros factores que no son de carácter económico, como la personalidad del estudiante, que incluye aspectos como tolerancia a la frustración y autoestima. Asimismo, se determina que los antecedentes familiares en educación son relevantes para el estudiante. Por otro lado, se establece que el factor académico o institucional, que incluye aspectos como horarios de clase, metodología de enseñanza y personal docente, también juegan un papel en la trayectoria académica del estudiante. Finalmente, el artículo concluye que es fundamental abordar estos desafíos para mejorar la retención estudiantil y fomentar el acceso a la educación superior en Centroamérica. \
*Contraste:* Este texto le da una mayor importancia a la situación económica del estudiante en función a la deserción de estudios superiores. Señala como la falta de dinero o los medios para obtenerlo son el principal causante de que una persona abandone la universidad. Mientras que en artículos como el de Marcos Estrada-Ruiz (2015) enfatizan las causas de deserción escolar desde el punto de vista social. Se destaca que las principales razones al tomar esta decisión son la presión social, responsabilidades familiares y la falta de apoyo institucional. Razones que a su vez son habladas por Lobos y Rodroguez (2022) pero como causantes secundarios. Es importante señalar que Estrada-Ruiz (2015) centra su estudio en mujeres mientras que Lobos y Rodriguez (2015) no separan su investigación por género. \
*Contribución:* Es interesante como ambos textos hacen alusión del papel que juega la institución como tal en si se deserta o no la universidad. El apoyo que el centro educativo pueda brindar ya sea con flexibilidad de pago, de horarios, personal capacitado en psicopedagogía,etc no se suele considerar como parte de la problemática ante la cantidad de personas que dejan los estudios sino que la culpa se suele colocar al estudiante. 

***Los jóvenes que desertan de la educación media: virajes y puntos de no retorno***\
*Resumen:* Este documento realizado por Marcos Estrada-Ruiz (2015) explora las experiencias de jóvenes mujeres que desertan de la educación media en Hermosillo, Sonora. A través de entrevistas biográficas, se identifican los factores que contribuyen a la deserción, como la presión social, las responsabilidades familiares y la falta de apoyo institucional. El estudio revela que muchas de estas jóvenes enfrentan vulnerabilidades significativas tras abandonar la escuela, lo que impacta sus trayectorias de vida. Además, se destaca la importancia de las relaciones familiares y el contexto social en la decisión de regresar a la educación. La investigación subraya la necesidad de abordar las desigualdades de género en el ámbito educativo.\
*Contraste:* Tanto el estudio realizado por Niebles (2023) acerca de la Teoría de los Sistemas Ecológicos de Bronfenbrenner como el de Estrada-Ruiz (2015) resaltan la falta de apoyo social y la carencia de políticas educativas que se involucren en el área. Sin embargo, la Teoría de los Sistemas Ecológicos no toma en cuenta la cultura ni factores sociales dentro para determinar los factores que causan la deserción universitaria. Esto debido a la complejidad de los factores. Por lo tanto, existe una discrepancia en la importancia del ambiente donde una persona se desarrolla y su impacto en la educación.\
*Contribución:* El artículo por Estrada-Ruiz (2015) representa la parte de la discusión que no es tan fácilmente cuantificable. Medir el impacto de una cultura sobre la educación no es un trabajo sencillo por lo que se estudian otras variables más concisas que brinden datos más concretos pero que aun se relacionan con el factor social. En tanto, estudios como este son de gran importancia para brindar eventualmente esa relación entre los resultados obtenidos y la parte social o cultural. Es recordatorio de que hay una parte que impacta al problema a investigar que no es tangible.

***La teoría de los sistemas ecológicos de Urie Bronfenbrenner como marco para comprender la deserción universitaria***\
*Resumen:* Los Sistemas Ecológicos de Urie Bronfenbrenner son descritos en el presente artículo realizado por Niebles (2013). En los últimos años se ha dado una creciente preocupación por la deserción universitaria en Colombia, dado que alrededor de solo los estudiantes que inician la educación superior logran graduarse. Usando la Teoría de los Sistemas Ecológicos de Bronfenbrenner se examinan los factores que contribuyen a este fenómeno. Entre los factores investigados se encuentran: los problemas económicos, falta de apoyo social y la deficiencia de las políticas educativas. Sin embargo, esta teoría no brinda apoyo para entender los aspectos más sociales y culturales, sólo los factores más inmediatos. Se destaca la importancia de un enfoque más integral que reconozca la complejidad del fenómeno por la interconexión de los distintos factores para poder crear reformas y desarrollar estrategias para prevenir el abandono escolar. \
*Contraste:* El enfoque de la investigación realizada acerca de la teoría anteriormente mencionada es el desarrollo de una persona y cómo este se ve influenciado por cinco sistemas que propone Bronfenbrenner. Este describe cómo los distintos círculos sociales entre más cercanos tienen un mayor impacto. Estos círculos sociales para Martinez-Otero no afectan por cercanía a la persona sino por el papel que tiene cada uno dentro de la vida de cada quien. Sin embargo, ambos consideran las mismas personas en los factores que describen.\
*Contribución:* Ambas maneras de analizar el impacto de los factores en una persona son de suma importancia para esta investigación ya que el propósito de la misma es relacionar dichos factores con la educación. Por este motivo, de que manera sea expresada esta conexión exactamente no es tal relevante, sino que existe y que efectivamente si impacta el objetivo de estudio.  

***Diversos condicionantes del fracaso escolar en la educación secundaria***\
*Resumen:* El texto aborda el tema del fracaso escolar en la educación secundaria. Se enfoca en la interacción de factores tanto individuales como contextuales que podrían afectar el rendimiento de un estudiante. El autor reúne información en base a investigaciones previas y reflexiones teóricas e identifica condicionantes como el contexto socioeconómico, las metodologías de enseñanza y la inteligencia emocional del estudiante como parte de los determinantes del rendimiento académico. Se realiza una crítica acerca de la visión tradicional de la inteligencia y el enfoque mecanicista de la educación. Se sugiere que se consideren más aspectos emocionales, morales y sociales. Las normas y herramientas actuales que buscan solventar este problema , no son suficientes por lo que se pide una revisión de los mismos. Sin embargo, desde una perspectiva más integral donde se combine la mejor atención a las necesidades individuales del estudiante como a la calidad de la educación recibida. \
*Contraste:* El texto “Modelo de condicionantes del fracaso escolar de Martinez-Otero” define el fracaso escolar como cuando el estudiante falla a alcanzar ciertos marcadores dependiendo de su nivel, edad y desarrollo en los centros educativos. Este fracaso es también parte de los temas que cubren Marlon Lobos y Judith Rodriguez (2022) como determinantes de la deserción estudiantil. Sin embargo, lo toman como un factor secundario; es decir, este junto con algún problema económico primordialmente son los que llevan a la persona estudiante a tomar esta decisión. Lo que es distinto a lo trabajado por Martinez-Otero quien busca determinar la causa de ese rezago académico. \
*Contribución:* A razón de tener tanto el material literario que respalda las razones del rezago académico y las consecuencias que la misma brindan, es posible estipular que la investigación a realizar es bastante completa. La unión de los factores a estudiar harán posible determinar que verdaderamente afecta a los estudiantes en su educación superior para finalmente salir de la misma.   

## Análisis estadísticos






### Análisis descriptivo


### Propuesta métodologica

### Construcción de fichas de resultados

