{
  "hash": "03567274fc3a5159f6e9faaaca734cb6",
  "result": {
    "engine": "knitr",
    "markdown": "---\neditor: \n  markdown: \n    wrap: 72\nfig-cap-location: bottom\nexecute:\n  freeze: auto\n  cache: true\n---\n\n# Bitácora 3: Experimentos y Modelaje\n\n\n## Parte de planificación\n### Análisis de modelación\n \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(janitor)\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(knitr)\nlibrary(ggridges)\nlibrary(treemapify)\n\ndf <- read_csv2(\"base_datos/universidades_europeas.csv\")\ndf <- df %>% clean_names()\n```\n:::\n\nEste es un gráfico de tipo heatmap que muestra la frecuencia de cada combinación de niveles académicos de padre y madre del estudiante, un color más oscuro significa mayor cantidad de observaciones de ese tipo. Además, está facetado por la categoría del estudiante (graduado, desertor o matriculado).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df %>% \n  mutate(target = case_when(\n    target == \"Dropout\" ~ \"Desertor\",\n    target == \"Enrolled\" ~ \"Matriculado\",\n    target == \"Graduate\" ~ \"Graduado\",\n    TRUE ~ NA\n  ))\n\n\ndf <- df %>% \n  mutate(mothers_qualification=case_when(\n    mothers_qualification== 1 ~ \"Educación Secundaria\",\n    mothers_qualification== 2 ~ \"Licenciatura\",\n    mothers_qualification== 3 ~ \"Grado\",\n    mothers_qualification== 4 ~ \"Master\",\n    mothers_qualification== 5~ \"Doctorado\",\n    mothers_qualification== 6 ~ \"9 - 12mo Año de Escolaridad - No Completado\",\n    mothers_qualification== 9 ~ \"12º Año de Escolaridad\",\n    mothers_qualification==10~ \"11º Año de Escolaridad - No Completado\",\n    mothers_qualification==11~ \"7º Año (Antiguo)\",\n    mothers_qualification==12~ \"11º Año de Escolaridad\",\n    mothers_qualification==13~ \"2º Año del curso complementario de secundaria\",\n    mothers_qualification==14~ \"10º Año de Escolaridad\",\n    mothers_qualification==18 ~ \"Curso de comercio general\",\n    mothers_qualification==19~ \"Educación Básica 3º Ciclo (9º/10º/11º Año) \n    o Equiv.\",\n    mothers_qualification==20~ \"Curso Complementario de Secundaria\",\n    mothers_qualification==22~ \"Curso técnico-profesional\",\n    mothers_qualification==25~ \"Curso Complementario de Secundaria - No \n    Concluido\",\n    mothers_qualification==27~ \"7º Año de Escolaridad\",\n    mothers_qualification==29~ \"9º Año de Escolaridad - No Completado\",\n    mothers_qualification==30~ \"8º Año de Escolaridad\",\n    mothers_qualification==31~ \"Curso General de Administración y Comercio\",\n    mothers_qualification==33~ \"Contabilidad y Administración Suplementaria\",\n    mothers_qualification==34~ \"Desconocido\",\n    mothers_qualification==35~ \"No sabe leer ni escribir\",\n    mothers_qualification==36~ \"Sabe leer sin tener el 4º Año de Escolaridad\",\n    mothers_qualification==37~ \"Educación Básica 1º Ciclo (4º/5º Año) o Equiv.\",\n    mothers_qualification==38~ \"Educación Básica 2º Ciclo (6º/7º/8º Año) o\n    Equiv.\",\n    mothers_qualification==39~ \"Curso de especialización tecnológica\",\n    mothers_qualification==40~ \"Educación Superior - Grado (1º Ciclo)\",\n    mothers_qualification==41~ \"Curso de estudios superiores especializados\",\n    mothers_qualification==42~ \"Curso técnico superior profesional\",\n    mothers_qualification==43~ \"Educación Superior - Máster (2º Ciclo)\",\n    mothers_qualification==44~ \"Educación Superior - Doctorado (3º Ciclo)\",\n    TRUE ~ \"Desconocido\"\n  ))\n\ndf <- df %>% \n  mutate(fathers_qualification=case_when(\n    fathers_qualification == 1 ~ \"Educación Secundaria\",\n    fathers_qualification  == 2 ~ \"Licenciatura\",\n    fathers_qualification == 3 ~ \"Grado\",\n    fathers_qualification == 4 ~ \"Master\",\n    fathers_qualification == 5~\"Doctorado\",\n    fathers_qualification == 6 ~ \"9 - 12mo Año de Escolaridad - No Completado\",\n    fathers_qualification == 9 ~ \"12º Año de Escolaridad\",\n    fathers_qualification==10~ \"11º Año de Escolaridad - No Completado\",\n    fathers_qualification==11~ \"7º Año (Antiguo)\",\n    fathers_qualification==12~ \"11º Año de Escolaridad\",\n    fathers_qualification==13~ \"2º Año del curso complementario de secundaria\",\n    fathers_qualification==14~ \"10º Año de Escolaridad\",\n    fathers_qualification==18 ~ \"Curso de comercio general\",\n    fathers_qualification==19~ \"Educación Básica 3º Ciclo (9º/10º/11º Año) \n    o Equiv.\",\n    fathers_qualification==20~ \"Curso Complementario de Secundaria\",\n    fathers_qualification==22~ \"Curso técnico-profesional\",\n    fathers_qualification==25~ \"Curso Complementario de Secundaria - No \n    Concluido\",\n    fathers_qualification==27~ \"7º Año de Escolaridad\",\n    fathers_qualification==29~ \"9º Año de Escolaridad - No Completado\",\n    fathers_qualification==30~ \"8º Año de Escolaridad\",\n    fathers_qualification==31~ \"Curso General de Administración y Comercio\",\n    fathers_qualification==33~ \"Contabilidad y Administración Suplementaria\",\n    fathers_qualification==34~ \"Desconocido\",\n    fathers_qualification==35~ \"No sabe leer ni escribir\",\n    fathers_qualification==36~ \"Sabe leer sin tener el 4º Año de Escolaridad\",\n    fathers_qualification==37~ \"Educación Básica 1º Ciclo (4º/5º Año) o Equiv.\",\n    fathers_qualification==38~ \"Educación Básica 2º Ciclo (6º/7º/8º Año) o \n    Equiv.\",\n    fathers_qualification==39~ \"Curso de especialización tecnológica\",\n    fathers_qualification==40~ \"Educación Superior - Grado (1º Ciclo)\",\n    fathers_qualification==41~ \"Curso de estudios superiores especializados\",\n    fathers_qualification==42~ \"Curso técnico superior profesional\",\n    fathers_qualification==43~ \"Educación Superior - Máster (2º Ciclo)\",\n    fathers_qualification==44~ \"Educación Superior - Doctorado (3º Ciclo)\",\n    TRUE ~ \"Desconocido\"\n  ))\n\n\ndf$mothers_qualification<-as.factor(df$mothers_qualification)\ndf$fathers_qualification<-as.factor(df$fathers_qualification)\n\nsum_mothers_qualification<-df %>% \n  mutate(mothers_qualification=fct_collapse(mothers_qualification, \n   \"Primaria completada\" = c(\"7º Año (Antiguo)\",\"7º Año de Escolaridad\", \n         \"Educación Básica 2º Ciclo (6º/7º/8º Año) o Equiv.\"),\n   \"Primaria no completado\"=c(\"Sabe leer sin tener el 4º Año de Escolaridad\", \n           \"Educación Básica 1º Ciclo (4º/5º Año) o Equiv.\"),\n   \"Secundaria completada\" =c(\"Educación Secundaria\", \"12º Año de Escolaridad\", \n           \"Curso Complementario de Secundaria\"),\n   \"Secundaria no completado\"=c(\"9 - 12mo Año de Escolaridad - No Completado\",\n\"11º Año de Escolaridad - No   Completado\",\"11º Año de Escolaridad\",\"2º Año del \ncurso complementario de secundaria\",\"Educación Básica 3º Ciclo (9º/10º/11º Año) \no Equiv.\", \"Curso Complementario de Secundaria - No Concluido\",\"9º Año de \nEscolaridad - No Completado\",\"8º Año de Escolaridad\",\"10º Año de Escolaridad\"),\n  \"Universidad completada\"= c(\"Licenciatura\",\"Grado\",\"Master\",\"Doctorado\",\n\"Educación Superior - Máster (2º Ciclo)\",\"Educación Superior - Grado \n(1º Ciclo)\",\"Educación Superior - Doctorado (3º Ciclo)\" ),\n  \"Cursos complementarios\"= c(\"Curso de comercio general\", \"Curso \ntécnico-profesional\", \"Curso General de Administración y Comercio\",\"Contabilidad\ny Administración Suplementaria\",\"Curso de especialización tecnológica\",\"Curso \nde estudios superiores especializados\", \"Curso técnico superior profesional\"),\n    \"No sabe leer ni escribir\" = c(\"No sabe leer ni escribir\")\n  )) %>% \n  mutate(mothers_qualification=fct_lump(mothers_qualification, n=9)) %>% \n  count(mothers_qualification, sort=TRUE) %>% \n  rename(nivel_educativo_madre=n)\n\nsum_fathers_qualification<-df %>% \n  mutate(fathers_qualification=fct_collapse(fathers_qualification, \n      \"Primaria completada\" = c(\"7º Año (Antiguo)\",\"7º Año de Escolaridad\", \n\"Educación Básica 2º Ciclo (6º/7º/8º Año) o Equiv.\"),\n      \"Primaria no completado\"= c(\"Sabe leer sin tener el 4º Año de Escolaridad\",\n\"Educación Básica 1º Ciclo (4º/5º Año) o Equiv.\"),\n      \"Secundaria completada\" =c(\"Educación Secundaria\", \"12º Año de Escolaridad\",\n\"Curso Complementario de Secundaria\"),\n      \"Secundaria no completado\"=c(\"9 - 12mo Año de Escolaridad - No Completado\", \n\"11º Año de Escolaridad - No Completado\",\"11º Año de Escolaridad\",\n\"2º Año del curso complementario de secundaria\",\n\"Educación Básica 3º Ciclo (9º/10º/11º Año) o Equiv.\", \"Curso Complementario de \nSecundaria - No Concluido\",\"9º Año de Escolaridad - No Completado\",\"8º\nAño de Escolaridad\",\"10º Año de Escolaridad\"),\n      \"Universidad completada\"=c(\"Licenciatura\",\"Grado\",\"Master\",\"Doctorado\",\n\"Educación Superior - Máster (2º Ciclo)\",\"Educación Superior - Grado (1º Ciclo)\",\n\"Educación Superior - Doctorado (3º Ciclo)\" ),\n      \"Cursos complementarios\"= c(\"Curso de comercio general\", \"Curso \ntécnico-profesional\", \"Curso General de Administración y Comercio\",\n\"Contabilidad y Administración Suplementaria\",\"Curso de especialización \ntecnológica\", \"Curso de estudios superiores especializados\", \"Curso técnico \nsuperior profesional\"),\n      \"No sabe leer ni escribir\" = c(\"No sabe leer ni escribir\")\n  )) %>% \n  mutate(fathers_qualification=fct_lump(fathers_qualification, n=9)) %>% \n  count(fathers_qualification, sort = TRUE) %>% \n  rename(nivel_educativo_padre=n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsum_fathers_qualification<-sum_fathers_qualification %>% \n  rename(nivel_de_estudios=fathers_qualification)\n\nsum_mothers_qualification<-sum_mothers_qualification %>% \n  rename(nivel_de_estudios=mothers_qualification)\n\nsum_qualification<-sum_mothers_qualification %>% \n  left_join(sum_fathers_qualification, by=\"nivel_de_estudios\") \n\ntarget_parents_qualification<-df %>% \n  mutate(mothers_qualification=fct_collapse(mothers_qualification,\n        \"Primaria completada\" = c(\"7º Año (Antiguo)\",\"7º Año de Escolaridad\", \n        \"Educación Básica 2º Ciclo (6º/7º/8º Año) o Equiv.\"),\n        \"Primaria no completado\"=c(\"Sabe leer sin tener el 4º Año de Escolaridad\", \"Educación Básica 1º Ciclo (4º/5º Año) o Equiv.\"),\n        \"Secundaria completada\" =c(\"Educación Secundaria\", \"12º Año de Escolaridad\", \"Curso Complementario de Secundaria\"),\n       \"Secundaria no completado\"=c(\"9 - 12mo Año de Escolaridad - No Completado\",\"11º Año de Escolaridad - No Completado\",\"11º Año de Escolaridad\",\"2º Año del curso complementario de secundaria\",\"Educación Básica 3º Ciclo (9º/10º/11º Año) o Equiv.\",\"Curso Complementario de Secundaria - No Concluido\",\"9º Año de Escolaridad - No Completado\", \"8º Año de Escolaridad\",\"10º Año de Escolaridad\"),\n      \"Universidad completada\"=c(\"Licenciatura\",\"Grado\",\"Master\",\"Doctorado\", \"Educación Superior - Máster (2º Ciclo)\",\"Educación Superior - Grado (1º Ciclo)\",\"Educación Superior - Doctorado (3º Ciclo)\" ),\n      \"Cursos complementarios\"= c(\"Curso de comercio general\", \"Curso técnico-profesional\", \"Curso General de Administración y Comercio\",\"Contabilidad y Administración Suplementaria\",\"Curso de especialización tecnológica\", \"Curso de estudios superiores especializados\", \"Curso técnico superior profesional\"),\n       \"No sabe leer ni escribir\" = c(\"No sabe leer ni escribir\")\n  )) %>% \n  mutate(fathers_qualification=fct_collapse(fathers_qualification,\n      \"Primaria completada\" = c(\"7º Año (Antiguo)\",\"7º Año de Escolaridad\", \"Educación Básica 2º Ciclo (6º/7º/8º Año) o Equiv.\"),\n      \"Primaria no completado\"=c(\"Sabe leer sin tener el 4º Año de Escolaridad\",\"Educación Básica 1º Ciclo (4º/5º Año) o Equiv.\"),\n       \"Secundaria completada\" =c(\"Educación Secundaria\", \"12º Año de Escolaridad\",\"Curso Complementario de Secundaria\"),\n       \"Secundaria no completado\"=c(\"9 - 12mo Año de Escolaridad - No Completado\",\"11º Año de Escolaridad - No Completado\",\"11º Año de Escolaridad\", \"2º Año del curso complementario de secundaria\", \"Educación Básica 3º Ciclo (9º/10º/11º Año) o Equiv.\", \"Curso Complementario de Secundaria - No Concluido\",\"9º Año de Escolaridad - No Completado\", \"8º Año de Escolaridad\",\"10º Año de Escolaridad\"),\n       \"Universidad completada\"=c(\"Licenciatura\",\"Grado\",\"Master\",\"Doctorado\",\"Educación Superior - Máster (2º Ciclo)\",\"Educación Superior - Grado (1º Ciclo)\", \"Educación Superior - Doctorado (3º Ciclo)\"),\n        \"Cursos complementarios\"= c(\"Curso de comercio general\", \"Curso técnico-profesional\", \"Curso General de Administración y Comercio\",\"Contabilidad y Administración Suplementaria\",\"Curso de especialización tecnológica\", \"Curso de estudios superiores especializados\", \"Curso técnico superior profesional\"),\n        \"No sabe leer ni escribir\" = c(\"No sabe leer ni escribir\")\n  )) %>% \n  group_by(target, mothers_qualification, fathers_qualification) %>% \n  summarise(count=n())\n\n\n\ngrafica_uno<-ggplot(target_parents_qualification, aes(x = mothers_qualification, y = fathers_qualification, fill = count)) + \n  geom_tile() + scale_fill_gradient(low=\"#AAE48D\",\n                                    high = \"#2B7308\",\n                                    guide = \"colorbar\" )+\n  facet_wrap(~ target) + labs(\n    x = \"Nivel educativo de la madre\",\n    y = \"Nivel educativo del padre\", \n    fill = \"Frecuencia\", title=\"Gráfica 1. Comparación del nivel \n    educativo de los padres y\\n el estado de los estudiantes\",\n    caption = \"Elaboración propia, Fuente: Realinho, et al (2022)\")+theme_bw()+\n  theme(plot.title = element_text(hjust = 0.5),\n    axis.text.x = element_text(size=6,angle=90,hjust=1))\nprint(grafica_uno)\n```\n\n::: {.cell-output-display}\n![](bitacora-3_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nEste es un gráfico de barras que recuenta la frecuencia absoluta de estudiantes que están al día o atrasados con los pagos de las cuotas, los identifica con colores distintos y los separa según su categoría de la variable objetivo. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df %>%\n  mutate(tuition_fees_up_to_date = case_when(\n    tuition_fees_up_to_date == 0 ~ \"No\",\n    tuition_fees_up_to_date == 1 ~ \"Si\",\n    TRUE ~ NA\n  ))\n\n\ngrafica_dos<-df %>%count(tuition_fees_up_to_date, target) %>% \n  ggplot(aes(x=target, y = n, fill = tuition_fees_up_to_date))+\n  geom_col(position = \"dodge\") + \n  theme_classic()+\n  labs(\n    x = \"Tipo de Estudiante\",\n    y = \"Frecuencia\",\n    fill = \"Cuotas al día\",\n    title = \"Gráfica 2. Relación entre persona deudora y resultado académico\"\n  ) +\n  scale_fill_manual(values = c(\"Si\" = \"#A2CD5A\",\"No\"=\"red\"))+\n  theme(legend.position = \"bottom\", \n        panel.border = element_rect(colour = \"black\", fill = NA),\n        plot.title = element_text(hjust = 0.5))\nprint(grafica_dos)\n```\n\n::: {.cell-output-display}\n![](bitacora-3_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nEste es otro gráfico de tipo heatmap, pero que ilustra la cantidad de estudiantes hallados en cada uno de los subgrupos generados al combinar la variable objetivo con una variable binaria (poseedor de beca o no). \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df %>%\n  mutate(scholarship_holder = case_when(\n    scholarship_holder == 0 ~ \"No\",\n    scholarship_holder == 1 ~ \"Si\",\n    TRUE ~ NA\n  ))\n\ngrafica_tres<-df %>%count(scholarship_holder, target) %>% \n  ggplot(aes(x=scholarship_holder, y = target, fill = n))+\n  geom_tile()+ \n  theme_classic() + \n  labs(x = \"Poseedor de Beca Socioeconómica\", y = \"Tipo de Estudiante\", fill = \"Frecuencia\", title = \"Gráfica 3. Frecuencia de Estudiantes Graduados, Matriculados \\n o Desertores según su categoría de beca\") + \n  scale_fill_continuous(low = \"skyblue\", high = \"darkblue\")+\n  theme(legend.position = \"right\",\n        panel.border = element_rect(colour = \"black\", fill=NA),\n        plot.title = element_text(hjust = 0.5))\nprint(grafica_tres)\n```\n\n::: {.cell-output-display}\n![](bitacora-3_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nEste es un gráfico de barras adicional que visualiza la frecuencia absoluta de estudiantes nacionales e internacionales y los distingue con colores dentro de cada categoría de la variable objetivo. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df %>%\n  mutate(international = case_when(\n    international == 0 ~ \"No\",\n    international == 1 ~ \"Si\",\n    TRUE ~ NA\n  ))\n\ngrafica_cuatro<-df %>%count(international, target) %>% \n  ggplot(aes(x=target, y = n, fill = international))+\n  geom_col(position = \"stack\") + \n  theme_classic()+\n  labs(\n    x = \"Tipo de Estudiante\",\n    y = \"Frecuencia\",\n    fill = \"Internacional\",\n    title = \"Gráfica 4. Comparación en la frecuencia del estado de los\\nestudiantes según su nacionalidad\"\n  ) +\n  scale_fill_manual(values = c(\"Si\" = \"#CD5555\",\"No\"=\"#BFEFFF\"))+\n  theme(legend.position = \"bottom\", \n        panel.border = element_rect(colour = \"black\", fill = NA),\n        plot.title = element_text(hjust = 0.5))\nprint(grafica_cuatro)\n```\n\n::: {.cell-output-display}\n![](bitacora-3_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nEl gráfico mostrado es de tipo densidad y es útil para mostrar la distribución de los créditos aprobados en el primer semestre según la categorías de la variable objetivo. Como existe una superposición significativa de las densidades, fue necesario reducir la opacidad. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrafico_cinco<-ggplot(df, aes(x = curricular_units_1st_sem_approved, fill=target))+\n  geom_density(alpha=0.6, color=NA)+\n  labs(\n    x = \"Créditos aprobados en el primer semestre\",\n    y = \"Densidad\",\n    fill = \"Categoría del estudiante\",\n    title = \"Densidades de créditos aprobados en primer semestre por tipo de estudiante\",\n    caption = \"Elaboración propia, Fuente: Realinho, et al (2022)\"\n  ) +cowplot::theme_cowplot()\nprint(grafico_cinco)\n```\n\n::: {.cell-output-display}\n![](bitacora-3_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nNuevamente se presenta un gráfico de barras sobre frecuencia absoluta que segmenta las categorías de la variable objetivo por una variable binaria diferenciada por color, en este caso el género.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf<- df %>%  \n  mutate (gender = case_when(\n    gender == \"0\" ~ \"Mujer\", \n    gender == \"1\" ~ \"Hombre\",\n    TRUE ~ NA\n  ))\n  \ngrafico_seis<-df %>% ggplot(aes(fill=gender, x=target))+geom_bar(stat=\"count\")+\n  theme_classic()+labs(\n    x=\"Tipo de estudiante\",\n    y= \"Cantidad de estudiantes\",\n    fill=\"Género\",\n    title = \"Gráfica 6. Distribución de estudiantes según su género.\",\n    caption = \"Elaboración propia, Fuente: Realinho, et al (2022)\"\n    )+\n  scale_y_continuous(breaks = seq(0, max(table(df$target)), by = 200))\nprint(grafico_seis)\n```\n\n::: {.cell-output-display}\n![](bitacora-3_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nEste gráfico de estilo scatter genera puntos en el plano cuyas coordenadas corresponden a las notas del primer y segundo semestre. El color de cada punto denota  la categoría de la variable objetivo a la que pertenece cada observación.Para apreciar mejor la información y recortar datos no relevantes, se expone solo las notas de 10 a 20.    \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df %>%\n  mutate(\n    curricular_units_1st_sem_grade = as.numeric(gsub(\"(\\\\d+\\\\.\\\\d+).*\", \"\\\\1\", curricular_units_1st_sem_grade)) %>%\n      round(2))\n\ndf <- df %>%\n  mutate(\n    curricular_units_2nd_sem_grade = as.numeric(gsub(\"(\\\\d+\\\\.\\\\d+).*\", \"\\\\1\", curricular_units_2nd_sem_grade)) %>%\n      round(2))\n\ngrafico_siete<-df %>% \nfilter(curricular_units_1st_sem_grade < 20,curricular_units_2nd_sem_grade > 10,  \n        curricular_units_2nd_sem_grade < 20,curricular_units_1st_sem_grade > 10,\n        target %in% c(\"Graduado\", \"Desertor\")) %>% \n  ggplot(aes(x=curricular_units_1st_sem_grade, y=curricular_units_2nd_sem_grade,\n             colour =target))+\n  geom_point()+theme_classic()+labs(\n    x=\"Nota del primer semestre\",\n    y=\"Nota del segundo semestre\",\n    title = \"Gráfica 7. Dispersión de promedios del primer año lectivo\\n \n    según la categoría del estudiante\",\n    color=\"Tipo de estudiante\",\n    caption = \"Elaboración propia, Fuente: Realinho, et al (2022)\"\n  )\nprint(grafico_siete)\n```\n\n::: {.cell-output-display}\n![](bitacora-3_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nEste es un gráfico de tipo treemap que ilustra las proporciones de estudiantes graduados, matriculados y desertores dentro de dos grandes grupos creados a partir de una distinción por variable binaria (desplazado o no desplazado). \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df %>%\n  mutate(displaced = case_when(\n    displaced == 0 ~ \"No desplazado\",\n    displaced == 1 ~ \"Desplazado\",\n    TRUE ~ NA\n  ))\n\ndf <- df %>% mutate(target = fct_relevel(target, \"Desertor\", \"Graduado\", \"Matriculado\")) \n\ndata_summary <- df %>%\n  group_by(displaced, target) %>%\n  summarise(count = n()) %>%\n  ungroup()\n\ngrafica_ocho<-ggplot(data_summary, aes(area = count, fill = target, \n                         label = paste(target, \"\\n\", count),\n                         subgroup = displaced)) +\n  geom_treemap(alpha = 0.8) +\n  geom_treemap_text(colour = \"white\", place = \"centre\", size = 10)+\n  facet_wrap(~displaced) +\n  labs(\n    title = \"Gráfica 8.Distribución de estudiantes según categoría y desplazamiento\",\n    fill = \"Estado\",\n    caption = \"Elaboración propia, Fuente: Realinho, et al (2022)\"\n  ) +\n  theme_minimal()+\n  theme(legend.position=\"none\")\n\nprint(grafica_ocho)\n```\n\n::: {.cell-output-display}\n![](bitacora-3_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nEste gráfico de tipo boxplot o diagrama de caja ilustra la distribución de las notas de admisión para cada categoría de la variable objetivo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df %>% mutate(target = fct_relevel(target, \"Desertor\", \"Matriculado\", \"Graduado\")) \n\ngrafica_nueve<-ggplot(df, aes(x = admission_grade, y = target, fill = target))+\n  geom_boxplot(alpha = 0.7)+\n  labs(\n    x = \"Nota de admisión\",\n    y = \"Categoría del estudiante\",\n    title = \"Gráfica 9.Distribución de las notas de admisión por categoría\",\n    caption = \"Elaboración propia, Fuente: Realinho, et al (2022)\"\n  )+\n  theme_minimal()+\n  theme(legend.position=\"none\")\n\nprint(grafica_nueve)\n```\n\n::: {.cell-output-display}\n![](bitacora-3_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nEste es un gráfico de densidad tipo ridgeline, el cual muestra las densidades de la edad al momento de ingreso a la universidad para cada categoría de la variable objetivo. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df %>% mutate(target = fct_relevel(target, \"Desertor\", \"Graduado\", \n                                         \"Matriculado\"))\n\ngrafica_diez<-ggplot(df, aes(x = age_at_enrollment, y = target, fill = target))+\n  geom_density_ridges(rel_min_height = 0.02, scale = 3, color=NA, alpha=0.7)+\n  xlim(15, 50)+\n  labs(\n    x = \"Edad de ingreso a la universidad\",\n    y = \"Categoría del estudiante\",\n    title = \"Gráfica 10.Densidades de edad de admisión por categoría de estudiante\",\n    caption = \"Elaboración propia, Fuente: Realinho, et al (2022)\"\n  )+\n  theme_minimal()+\n  theme(legend.position=\"none\")\n  print(grafica_diez)\n```\n\n::: {.cell-output-display}\n![](bitacora-3_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nEsta tabla contiene la frecuencia absoluta de cada categoría de la variable objetivo y calcula la media, mediana y desviación estándar de las calificaciones obtenidas por los estudiantes en el primer semestre de universidad. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabla_cuatro <- df %>%  group_by(target) %>% \n  summarise(\n    Media = mean(curricular_units_1st_sem_grade, na.rm=TRUE),\n    Mediana = median(curricular_units_1st_sem_grade, na.rm=TRUE),\n    DesviaciónEstándar = sd(curricular_units_1st_sem_grade, na.rm = TRUE),\n    N = n()\n  )\ntabla_cuatro <- tabla_cuatro %>%  filter(!is.na(target)) %>% \n  arrange(desc(N))\n\nkable(tabla_cuatro)\n```\n\n::: {.cell-output-display}\n\n\n|target      |     Media| Mediana| DesviaciónEstándar|    N|\n|:-----------|---------:|-------:|------------------:|----:|\n|Graduado    | 13.962906|    12.9|          15.278949| 2209|\n|Desertor    |  7.458248|    10.8|           8.562162| 1421|\n|Matriculado | 11.148388|    12.0|           5.266920|  794|\n\n\n:::\n:::\n\n\nSimilarmente, esta tabla recuenta la cantidad de estudiantes por género y calcula las medidas de tendencia central para la nota de cada grupo en los primeros dos semestres de universidad. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabla_cinco <- df %>%  group_by(gender) %>% \n  summarise(\n    N = n(),\n    Media_I = mean(curricular_units_1st_sem_grade, na.rm=TRUE),\n    Mediana_I = median(curricular_units_1st_sem_grade, na.rm=TRUE),\n    DesviaciónEstándar_I = sd(curricular_units_1st_sem_grade, na.rm = TRUE),\n    Media_II = mean(curricular_units_2nd_sem_grade, na.rm=TRUE),\n    Mediana_II = median(curricular_units_2nd_sem_grade, na.rm=TRUE),\n    DesviaciónEstándar_II = sd(curricular_units_2nd_sem_grade, na.rm = TRUE)\n  )\ntabla_cinco <- tabla_cinco %>%  filter(!is.na(gender)) %>% \n  arrange(desc(N))\n\nkable(tabla_cinco)\n```\n\n::: {.cell-output-display}\n\n\n|gender |    N|   Media_I| Mediana_I| DesviaciónEstándar_I|  Media_II| Mediana_II| DesviaciónEstándar_II|\n|:------|----:|---------:|---------:|--------------------:|---------:|----------:|---------------------:|\n|Mujer  | 2868| 12.241307|      12.4|            13.433039| 13.632374|      12.33|              20.73809|\n|Hombre | 1556|  9.759627|      11.8|             9.971996|  9.424743|      11.57|              11.66548|\n\n\n:::\n:::\n\n\nLa última tabla recopila las cifras correspondientes a la cantidad de estudiantes presentes en cada curso contemplado en la base de datos, así como qué número de estudiantes pertenecen a cada categoría de la variable objetivo por curso. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n df <- df %>% \n   mutate(course=case_when(\n     course ==33  ~ \"Tecnologías de producción de biocombustibles\",\n     course ==171  ~ \"Animación y Diseño Multimedia\",\n     course ==8014  ~ \"Servicio Social (asistencia nocturna)\",\n     course ==9003  ~ \"Agronomía\",\n     course ==9070  ~ \"Diseño de comunicación\",\n     course ==9085  ~ \"Enfermería Veterinaria\",\n     course ==9119  ~ \"Ingeniería Informática\",\n     course ==9130  ~ \"Equinicultura\",\n     course ==9147  ~ \"Administración\",\n     course ==9238  ~ \"Servicio Social\",\n     course ==9254  ~ \"Turismo\",\n     course ==9500  ~ \"Enfermería\",\n     course ==9556  ~ \"Odontología\",\n     course ==9670  ~ \"Gerencia de Publicidad y Marketing\",\n     course ==9773  ~ \"Periodismo y Comunicación\",\n     course ==9853  ~ \"Educación básica\",\n     course ==9991  ~ \"Administración (asistencia nocturna)\"\n   ))\n \ntabla_seis <- df %>% group_by(course) %>% \n  summarise(Cantidad = n(),\n            Desertor = sum(target == \"Desertor\"),\n            Graduado = sum(target == \"Graduado\"),\n            Matriculado = sum(target == \"Matriculado\"))\ntabla_seis <- tabla_seis %>%\n  filter(!is.na(course)) %>%\n  rename(Curso = course) %>%\n  arrange(desc(Cantidad))\n\n\nkable(tabla_seis)\n```\n\n::: {.cell-output-display}\n\n\n|Curso                                        | Cantidad| Desertor| Graduado| Matriculado|\n|:--------------------------------------------|--------:|--------:|--------:|-----------:|\n|Enfermería                                   |      766|      118|      548|         100|\n|Administración                               |      380|      134|      138|         108|\n|Servicio Social                              |      355|       65|      248|          42|\n|Enfermería Veterinaria                       |      337|       90|      172|          75|\n|Periodismo y Comunicación                    |      331|      101|      196|          34|\n|Administración (asistencia nocturna)         |      268|      136|       78|          54|\n|Gerencia de Publicidad y Marketing           |      268|       95|      125|          48|\n|Turismo                                      |      252|       96|      115|          41|\n|Diseño de comunicación                       |      226|       51|      133|          42|\n|Animación y Diseño Multimedia                |      215|       82|       96|          37|\n|Servicio Social (asistencia nocturna)        |      215|       71|      123|          21|\n|Agronomía                                    |      210|       86|       87|          37|\n|Educación básica                             |      192|       85|       57|          50|\n|Ingeniería Informática                       |      170|       92|       14|          64|\n|Equinicultura                                |      141|       78|       42|          21|\n|Odontología                                  |       86|       33|       36|          17|\n|Tecnologías de producción de biocombustibles |       12|        8|        1|           3|\n\n\n:::\n:::\n\n\n#### Construcción de fichas de resultados\n\n1.**FICHA 6**  \\\n\n- **Nombre de su hallazgo/resultado:** Relación significativa entre el género de los estudiantes y su permanencia en la carrera\\\n\n- **Resumen en una oración:** la cantidad de estudiantes mujeres graduadas es significativamente mayor a la cantidad de estudiantes hombres graduados  \\\n\n- **Principal característica:** En este gráfico se observan dos variables categóricas,  el género y el tipo de estudiante\\\n\n- **Problemas o posibles desafíos:** Al considerar sólo dos géneros, existe una parte de la población que queda totalmente fuera del estudio. Además, el análisis de este resultado considera una investigación mucho más social y cultural. Esto dado que distintas culturas y constructos sociales imponen ciertas restricciones y expectativas ante la educación para cada género.\\\n\n- **Resumen en un párrafo:** El gráfico #6 ilustra si el género juega un papel fundamental en la educación superior. Se puede concluir que de las personas graduadas la mayor cantidad son mujeres. La diferencia de este número es significativa en comparación de los hombres en la misma categoría. Según la investigación realizada por Landeta, et al (2011) una de las variables con mayor influencia en el rendimiento académico probó ser el género, siendo las mujeres aquellas con un rendimiento académico mayor en comparación de sus compañeros hombres. Exactamente lo que está siendo visualizado en el gráfico. Además, se entiende que no hay una diferencia significativa entre géneros a la hora de desertar.\\\n\n\n2. **FICHA 7**\\\n\n- **Nombre de su hallazgo/resultado:** Vínculo entre las notas del primer año y la decisión de continuar sus estudios superiores o desertar \\\n\n- **Resumen en una oración:** Entre más alta sea la nota tanto del primer como del segundo semestre, es más posible que el estudiante se gradúe. \\\n\n- **Principal característica:** Se considera la nota promedio de cada semestre, donde la nota más alta es 20 puntos\\\n\n- **Problemas o posibles desafíos:** En esta gráfica solo se consideran las notas del primer año, lo que no es significativo al rendimiento académico a través de toda la vida universitaria de cada estudiante. Las adaptaciones de cada persona a un ambiente nuevo, dado que es el primer año, varían. Solo considerar estas dos calificaciones puede ser insuficiente para analizar problemas en el desempeño académico \\\n\n- **Resumen en un párrafo:** Basado en el gráfico #7, es posible concluir que los estudiantes con notas más altas durante tanto el primer como el segundo semestre son aquellos que con mayor frecuencia se gradúan. Es decir, aquellos estudiantes con notas más bajas son más propensos a abandonar la educación superior.  Esta tendencia, de mejores notas en las personas que eventualmente se gradúan se expone tanto por Martinez-Otero (2009), como por Lobos y Rodriguez (2022). Aunque la importancia que ambos textos le dan a este factor varía, ambos están de acuerdo en que el rendimiento académico si forma parte de la decisión que es desertar. Además, Landeta, et al (2011) propone que el promedio (nota) y el género son las variables con una mayor correlación conforme al rendimiento académico.\\\n\n3. **FICHA 8**\\\n\n- **Nombre de su hallazgo/resultado:** Incidencia sobre la permanencia en la carrera de la necesidad de desplazamiento a la universidad.\\\n\n- **Resumen en una oración:** hay una mayor proporción de graduados en el grupo de estudiantes que necesitaron desplazarse para asistir a la universidad.\\\n\n- **Principal característica:** usar un gráfico facetado de tipo treemap facilita la interpretación visual y el análisis cuantitativo de la distribución de estudiantes graduados, matriculados y desertores según un criterio binario (tuvo la necesidad de desplazarse para asistir a la universidad o no). \\\n\n- **Problemas o posibles desafíos:** la frecuencia absoluta de estudiantes desplazados es mayor que la de no desplazados, por lo que mayores cifras en cierta categoría no necesariamente indican una tendencia. Sin embargo, esto se mitiga con el componente visual del gráfico, pues el área que ocupa cada categoría ilustra el porcentaje que representa en su respectivo grupo.\\\n\n- **Resumen en un párrafo:** Agrupando los estudiantes entre aquellos que tuvieron que desplazarse para asistir a la universidad y los que no, luego clasificándolos por su estado en la carrera (graduado, matriculado o desertor) y representando estos datos en el gráfico #8 facetado de tipo treemap, se revelaron comportamientos interesantes. Primero, es destacable que entre los desplazados existe una menor cantidad de desertores que en los no desplazados, aunque en términos absolutos existen más estudiantes del primer grupo que del segundo. Otro resultado llamativo es que, dentro de los desplazados, la categoría de estudiantes graduados representan alrededor del 54,57%, mientras que en los no desplazados, los graduados componen el 44,29%. Lo anterior parece indicar que existe una mayor probabilidad de graduarse entre los estudiantes que tuvieron que mudarse para recibir una educación superior. Esto contradice los resultados de Lobos y Rodríguez (2022), quienes argumentan que los costos de alquiler y transporte son algunos de los principales obstáculos que enfrentan los estudiantes para continuar con su carrera.\\\n\n4. **FICHA 9**\\\n\n- **Nombre de su hallazgo/resultado:** Importancia de la nota de admisión sobre la probabilidad de que un estudiante se gradúe.\\\n\n- **Resumen en una oración:** La mediana de las notas de admisión de los estudiantes graduados fue más alta que la de aquellos que desertaron o siguen matriculados. \\\n\n- **Principal característica:** El uso de un diagrama de caja permite visualizar fácilmente el comportamiento de la nota de admisión en las tres categorías de estudiantes, incluyendo los cuartiles y los valores atípicos.\\\n\n- **Problemas o posibles desafíos:**  La existencia de valores atípicos muy altos en la categoría de desertor demuestra que este resultado es solo una tendencia general y no una garantía de que una mejor nota de admisión implique graduarse.\\\n\n- **Resumen en un párrafo:**Al graficar la distribución de las notas de admisión según la categoría final del estudiante mediante un diagrama de cajas, se obtuvo un resultado previsible, aunque tal vez la tendencia no es tan fuerte como se esperaba. Es evidente que el valor de la mediana para los estudiantes graduados es mayor que el de los demás grupos. Además, en el tercer cuartil de la categoría de graduados están contenidos valores más altos que en las otras dos. Estos resultados concuerdan con los hallazgos de Montero, Villalobos y Valverde (2007), que determinaron que el promedio de admisión tiene una relación positiva con el desempeño académico más adelante en la carrera. Sin embargo, la similitud de los “bigotes” entre las tres clasificaciones, lo cual indica una variabilidad similar de los valores en los tres grupos, así como la presencia de valores atípicos muy altos entre los desertores, hacen cuestionar la firmeza de esta tendencia. \\\n\n\n5. **FICHA 10**\\\n\n- **Nombre de su hallazgo/resultado:** Influencia de la edad de ingreso a la universidad sobre la permanencia en la carrera.\\\n\n- **Resumen en una oración:** Una menor edad al momento de entrar a la universidad se relaciona con una mayor posibilidad de permanecer en la carrera.\\\n\n- **Principal característica:** Un gráfico de densidad de tipo ridgeline es más apropiado que uno convencional para distinguir la distribución de las categorías dada la concentración de los datos en la franja de 17 a 23 años.\\\n\n- **Problemas o posibles desafíos:**  Fue necesario limitar el alcance del gráfico a un máximo de 50 años, pues de no hacerlo era más difícil apreciar el comportamiento de los datos en rangos más relevantes y reducidos, como el de 17 a 25 años. Además, solo la categoría de desertor tenía una densidad perceptible para valores más altos que 50.\\\n\n- **Resumen en un párrafo:**La representación mediante el gráfico #10 tipo ridgeline de la densidad de las edades de admisión a la universidad según la categoría del estudiante revela tendencias significativas. Un resultado predecible es el hecho de que en todos los grupos, la mayor densidad ocurre entre los 18 y los 20 años, lo cual no es sorprendente dado que una gran cantidad de los estudiantes que ingresan a las universidades acaban de concluir los estudios secundarios. Más interesante es la distribución de la densidad del grupo de desertores, que son la categoría con mayor densidad después de los 25 años y los únicos con una densidad apreciable más allá de los 42 años. Por el contrario, la gran mayoría de los estudiantes graduados o matriculados entraron a la universidad con menos de 25 años.\\\n\n6. **FICHA 11**\\\n\n- **Nombre de su hallazgo/resultado:** Diferencias entre las notas de estudiantes graduados, desertores y matriculados.\\\n\n- **Resumen en una oración:**  Los estudiantes graduados presentan una media de notas en el primer semestre significativamente mayor que los desertores y matriculados.\\\n\n- **Principal característica:** Se considera el promedio ponderado al final del primer semestre junto con las materias reprobadas.\\\n\n- **Problemas o posibles desafíos:**  Hay una amplia variabilidad en las notas, especialmente con los graduados que presentan una desviación estándar relativamente grande a comparación de su media y mediana, lo cual sugiere que existen algunos impactos complementarios que afectan el desempeño.\\\n\n- **Resumen en un párrafo:**En el análisis de las notas entre estudiantes graduados, desertores y matriculados, se puede observar que son los graduados los que presentan una mayor media de notas en el primer semestre y los desertores la más baja lo cual sugiere que el impacto que tienen estas notas puede afectar el desempeño a futuro del estudiante llegando a la conclusión de desertar sus estudios. La desviación estándar de los graduados sugiere que hay algunas personas con notas bastante altas que se graduaron así como personas que presentan notas suficientes para graduarse pero no sobresalientes. Los datos de los estudiantes matriculados es el que se mantiene más consistente siendo este un grupo más interesante de analizar.\\\n\n7. **FICHA 12**\\\n\n- **Nombre de su hallazgo/resultado:** Comparación del desempeño académico en un año entre géneros.\\\n\n- **Resumen en una oración:**  Las estudiantes del género femenino presentan una media de notas más alta que los estudiantes masculinos en un año lectivo.\\\n\n- **Principal característica:** Se considera el promedio ponderado total por semestre de los estudiantes, considerando tanto graduados, desertores y matriculados.\\\n\n- **Problemas o posibles desafíos:**Se tiene aproximadamente el doble de registros de estudiantes femeninas que masculinos lo cual puede generar una escasez de información por parte del género masculino.\\\n\n- **Resumen en un párrafo:** El análisis muestra que las estudiantes del género femenino tienen un rendimiento superior académicamente al de los estudiantes masculinos en ambos semestres sin embargo presentan una mayor desviación estándar lo cual puede significar varios aspectos los cuales se deben profundizar. Las desviaciones de los estudiantes masculinos son significativamente inferiores que las de las estudiantes femeninas significando así que se tiene un registro más consistente en sus notas. Note que además no se está separando la información según el tipo de estudiante y dado que hay más estudiantes femeninos graduados que masculinos esto justifica muy bien la diferencia entre estas características.\\\n\n8. **FICHA 13**\\\n\n- **Nombre de su hallazgo/resultado:**  Clasificación de los estudiantes según la materia cursada.\\\n\n- **Resumen en una oración:**  Muestra la cantidad de estudiantes en diferentes cursos y su clasificación según su deserción o graduación.\\\n\n- **Principal característica:** Se destacan los cursos con mayor deserción en el área de administración y enfermería.\\\n\n- **Problemas o posibles desafíos:**Hay cursos que presentan una muy baja cantidad de estudiantes y por otra parte otros cursos presentan una muy alta cantidad de estudiantes como el de enfermería por lo que la variabilidad de los datos resulta un desafío para identificar los factores que generan la deserción estudiantil.\\\n\n- **Resumen en un párrafo:** La tabla proporciona los registros de los estudiantes que cursaron algunas materias según sus carreras y muestran el resultado en la categoría del estudiante al culminar el curso, donde algunos de estos deciden desertar la carrera universitaria y otros deciden continuar. Podemos observar que los cursos con mayor cantidad de estudiantes matriculados son enfermería y administración siendo este último el de mayor porcentaje de deserción. Se observan que los cursos con mayor cantidad de personas graduadas son enfermería y servicio social mientras que además de administración es en el área de enfermería y comunicación donde se encuentra la mayor deserción estudiantil.\\\n\n\n#### Ordenamiento de los elementos de reporte\n\n\n\n|                       |                                                                                                                      Elementos de Reporte                                                                                                                      |                                                                                                                                                                                                                       |\n|:---------------------:|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|\n|          Tipo         |                                                                                                                            Primarios                                                                                                                           | Secundarios                                                                                                                                                                                                           |\n|        **Teorías**        |                                                                                                 Modelo de Condicionantes del Fracaso esocolar de Martínez Otero                                                                                                | Teoría Ecológica de Urie Bronferbrenner                                                                                                                                                                               |\n|         **Ideas**         |                                                                                    Los factores económicos son responsables de la continuación de estudios superiores. Lobos                                                                                   | La deserción escolar en jóvenes mujeres está influenciada por factores sociales, económicos y familiares que afectan su trayectoria educativa. Estrada-Ruiz                                                           |\n| **Resultados de Autores** |             Existen diferencia marcadas entre estudiantes becados y no becados respecto a varios factores asociados al rendimiento académico, pero no necesariamente dictan tendencias sobre el promedio de calificaciones del estudiante. Garbanzo            |                                                                                                                                                                                                                       |\n|                       | El índice inteligencia emocional y el promedio de admisión tienen relación positiva con el desempeño, mientras que la evaluación centrada en exámenes y la enseñanza enfocada en clases magistrales tuvieron efectos negativos en el desempeño. Montero Rojas. | Los factores con mayor influencia sobre el desempeño académico de estudiantes universitarios son el género y el deseo de estudiar un posgrado. Izar Landeta.                                                          |\n| **Métodos**               | Predicting Student Dropout and Academic Success; base de datos por Realinho, et al (2022)                                                                                                                                                                      | Los modelos multinivel son la metodología más adecuada para tratar datos jerárquicos en la investigación educativa, superando las restricciones de los modelos de regresión lineal tradicionales. Murillo Torrecilla. |\n|                       | Generación de gráficas (Grolemund, 2017)                                                                                                                                                                                                                       |                                                                                                                                                                                                                       |\n|                       | Creación de tablas(Grolemund, 2017)                                                                                                                                                                                                                            | Impacto positivo del uso de tecnologías de la información y la comunicación en el rendimiento académico de estudiantes universitarios. Martha Jiménez                                                                 |\n|                       | Descripción de gráficos y tablas creadas                                                                                                                                                                                                                       |                                                                                                                                                                                                                       |\n| **Resultados Propios**    | Impacto de la obtención de una beca socioeconómica en la permanencia en la universidad                                                                                                                                                                         | Relación entre la completitud de los estudios superiores de ambos padres y la permanencia del estudiante en la carrera                                                                                                |\n|                       | Relación entre cumplimiento de cuotas escolares y permanencia del estudiante en la carrera.                                                                                                                                                                    | Independencia entre el origen del estudiante y la permanencia en la carrera.                                                                                                                                          |\n|                       | Relación entre los créditos aprobados en el primer semestre de carrera universitaria y la permanencia en la carrera                                                                                                                                            | Comparación del desempeño académico en un año entre géneros.                                                                                                                                                          |\n|                       | Relación significativa entre el género de los estudiantes y su permanencia en la carrera                                                                                                                                                                       | Diferencias entre las notas de estudiantes graduados, desertores y matriculados.                                                                                                                                      |\n|                       | Vínculo entre las notas del primer año y la decisión de continuar sus estudios superiores o desertar                                                                                                                                                           | Diferencias entre las notas de estudiantes graduados, desertores y matriculados.                                                                                                                                      |\n|                       | Importancia de la nota de admisión sobre la probabilidad de que un estudiante se gradúe.                                                                                                                                                                       | Influencia de la edad de ingreso a la universidad sobre la permanencia en la carrera.                                                                                                                                 |\n\n**Tabla ordenada**\n\n| **Sección**      | **Temas a tratar**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |\n|--------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|\n| **Introducción** | 1. Modelo de condicionantes del fracaso escolar de Martinez-Otero (primario)<br><br>2. Los factores económicos son responsables de la continuación de estudios superiores. Lobos. (primario)<br><br>3. La deserción escolar en jóvenes mujeres está influenciada por factores sociales, económicos y familiares que afectan su trayectoria educativa. Estrada-Ruiz (secundario)<br><br>4. Teoría ecológica de Urie Bronfenbrenner (secundario)<br><br>5. Existen diferencias marcadas entre estudiantes becados y no becados respecto a varios factores asociados al rendimiento académico, pero no necesariamente dictan tendencias sobre el promedio de calificaciones del estudiante. Garbanzo (primario)<br><br>6. Los factores con mayor influencia sobre el desempeño académico de estudiantes universitarios son el género y el deseo de estudiar un posgrado. Izar Landeta. (secundario)<br><br>7. El índice inteligencia emocional y el promedio de admisión tienen relación positiva con el desempeño, mientras que la evaluación centrada en exámenes y la enseñanza enfocada en clases magistrales tuvieron efectos negativos en el desempeño. Montero Rojas. (principal)1                                                                                                                                                                                                                                                                                                                                        |\n| **Metodología**  | 1. Predicting Student Dropout and Academic Success; base de datos por Realinho, et al (2022) (principal)<br><br>2. Generación de gráficas (Grolemund, 2017) (principal)<br><br>3. Creación de tablas (Grolemund, 2017)<br><br>4. Los modelos multinivel son la metodología más adecuada para tratar datos jerárquicos en la investigación educativa, superando las restricciones de los modelos de regresión lineal tradicionales. Murillo Torrecilla (secundario)<br><br>5. Impacto positivo del uso de la tecnologías de la información y la comunicación en el rendimiento académico de estudiantes universitarios. Martha Jiménez (secundario)<br><br>6. Descripción de gráficos y tablas creadas (primario)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |\n| **Resultados**   | 1. Relación entre la completitud de los estudios superiores de ambos padres y la permanencia del estudiante en la carrera (secundario)<br><br>2. Relación entre cumplimiento de cuotas escolares y permanencia del estudiante en la carrera (primario)<br><br>3. Impacto de la obtención de una beca socioeconómica en la permanencia en la universidad (primerio)<br><br>4. Independencia entre el origen del estudiante y la permanencia en la carrera (secundario)<br><br>5. Relación entre los créditos aprobados en el primer semestre de carrera universitaria y la permanencia en la carrera (primario)<br><br>6. Diferencias entre las notas de estudiantes graduados, desertores y matriculados (secundario)<br><br>7. Relación significativa entre el género de los estudiantes y su permanencia en la carrera (primario)<br><br>8. Comparación del desempeño académico en un año entre géneros (secundario)<br><br>9. Vínculo entre las notas del primer año y la decisión de continuar sus estudios superiores o desertar (primario)<br><br>10. Incidencia sobre la permanencia en la carrera de la necesidad de desplazamiento a la universidad (secundario)<br><br>11. Importancia de la nota de admisión sobre la probabilidad de que un estudiante se gradúe (primario)<br><br>12. Influencia de la edad de ingreso a la universidad sobre la permanencia en la carrera (secundario)<br><br>13. Importancia de la última materia cursada en la decisión de continuar con los estudios o desertar (secundario) |\n                                                                                                                                                                             \n\n## Parte de escritura\n\n### Introducción\n\nLa educación es el motor de cualquier sociedad, sirve como mecanismo para expandir el conocimiento y enriquecer la cultura. A su vez es una herramienta capaz de combatir la pobreza, mejorar la salud y lograr la igualdad de género. Sin embargo, una problemática creciente es la cantidad de personas que no completan sus estudios, ya sean de primaria, secundaria o educación superior. La formación de profesionales es un peldaño fundamental en el crecimiento económico y exploración del conocimiento para cualquier nación por lo que la permanencia en los centros de educación universitaria es fundamental. No obstante, no es un trabajo sencillo encontrar las causas del abandono de esta etapa de la educación para de esta manera ayudar a contrarrestarlas. Es así, que se busca analizar la manera en que los factores sociales, económicos, académicos y familiares influyen en la trayectoria académica de la persona estudiante. \\\n\nLa decisión de abandonar los estudios universitarios es el resultado de la interacción de factores individuales y contextuales que podrían afectar el rendimiento de un estudiante. Tal como lo describe Martin-Otero (2009) en su investigación acerca de los condicionantes del fracaso de la educación secundaria. Mientras que los niveles de educación comentados son distintos, los principios que expone se extienden a cada nivel. Primeramente, se define el fracaso escolar como el punto en que el estudiante falla en alcanzar ciertos marcadores dependiendo de su nivel, edad y desarrollo en los centros educativos. Al intentar encontrar los determinantes de ese fracaso, se presenta un problema: la interconección de los factores y la complejidad de separar la afectación de cada uno de los condicionantes. El autor reúne información en base a investigaciones previas y reflexiones teóricas e identifica condicionantes como el contexto socioeconómico, las metodologías de enseñanza y la inteligencia emocional del estudiante como parte de los determinantes del rendimiento académico. Se sugiere que si se quiere disminuir el fracaso escolar es necesario un enfoque integral que considere aspectos emocionales, morales y sociales. \\\n\nAsimismo, un aspecto importante a considerar son los factores económicos. Estos, según Lobos (2022) son los más influyentes en la deserción estudiantil a nivel universitario en Centroamérica. Las dificultades económicas son limitantes para los estudiantes de la educación superior y los obliga a tomar decisiones acerca de su permanencia o retiro de las universidades. El autor argumenta que los altos costos de matrícula, materiales, transporte, alimentación y demás gastos son el principal obstáculo que enfrentan los estudiantes para continuar con su carrera, así como lo es la imposibilidad de estudiar y trabajar simultáneamente. Esto apunta a que la falta de dinero o los medios para obtenerlo son el principal causante de que una persona abandone la universidad. Sin embargo, se destacan otros factores que no son de carácter económico, como la personalidad del estudiante, que incluye aspectos como tolerancia a la frustración y autoestima. Asimismo, se determina que los antecedentes familiares en educación son relevantes para el estudiante. Por otro lado, se establece que el factor académico o institucional, que incluye aspectos como horarios de clase, metodología de enseñanza y personal docente, también juegan un papel en la trayectoria académica del estudiante. \\\n\nMientras tanto, en artículos como el de Marcos Estrada-Ruiz (2015) se enfatizan las causas de deserción escolar desde el punto de vista social. Se destaca que las principales razones al tomar esta decisión son la presión social, responsabilidades familiares y la falta de apoyo institucional. Razones que a su vez son consideradas por Lobos y Rodriguez (2022) pero como causantes secundarios. Es importante señalar que Estrada-Ruiz (2015) centra su estudio en mujeres. El estudio revela que muchas de estas jóvenes enfrentan vulnerabilidades significativas tras abandonar la escuela, lo que impacta sus trayectorias de vida. Además, se destaca la importancia de las relaciones familiares y el contexto social en la decisión de regresar a la educación. La investigación subraya la necesidad de abordar las desigualdades de género en el ámbito educativo.\\\n\nTanto el estudio realizado por Niebles (2023) acerca de la Teoría de los Sistemas Ecológicos de Bronfenbrenner como el de Estrada-Ruiz (2015) resaltan la falta de apoyo social y la carencia de políticas educativas que se involucren en el área. No obstante, este enfoque social es minimizado en estudios como el realizado por Niebles (2023) acerca de la Teoría de los Sistemas Ecológicos de Bronfenbrenner quien acepta el involucramiento que tiene el ambiente social y cultural donde se desarrolla el individuo, pero lo descarta dentro de su investigación debido a su complejidad. En esta fuente se destaca la importancia de un enfoque más integral que reconozca la complejidad del fenómeno por la interconexión de los distintos factores para poder crear reformas y desarrollar estrategias para prevenir el abandono escolar. Esto mediante la investigación de los factores con consecuencias más inmediatas como lo son los problemas económicos, falta de apoyo social y la deficiencia de las políticas educativas. Además, define cinco sistemas compuestos por los distintos tipos de relación que se pueden tener entre los individuos y dicta que entre más cercana sea la relación esta tiene un mayor impacto sobre la persona. Bronfenbrenner considera estos cinco sistemas ecológicos: el microsistema, macrosistema, exosistema, y el mesosistema. Cada uno influye a su manera en el desarrollo del individuo; por ejemplo, el microsistema es el más influyente ya que abarca su entorno inmediato; es decir, su familia, escuela, amistades, etc. El macrosistema en cambio, es más ambiental, en este se discuten los factores culturales, el estatus socioeconómico, origen etnico, entre otros. A diferencia de la visión de Martinez-Otero cuya opinión radica en que estos círculos sociales no son afectados por cercanía sino por su papel dentro de la vida de cada quien. \\\n\nDesde una perspectiva práctica, artículos como el de Garbanzo Vargas (2013) analizan los posibles factores de la deserción estudiantil a partir de una encuesta. La autora observa el rendimiento académico como indicador de la calidad de la educación y define de manera general algunos componentes teóricos relevantes: rendimiento académico, nivel socioeconómico y la relación entre ambos. Luego, plantea una encuesta que contempla: sexo, edad, beca, colegio de procedencia, satisfacción con la carrera, hábitos de estudio, nivel socioeconómico, satisfacción con los profesores, convivencia familiar, nivel educativo de los padres, nota de admisión, entre otros. A la vez, se distinguió entre aquellos estudiantes con la máxima categoría de beca y aquellos que no solicitaron beca. Se concluyó que en las carreras de alta demanda, no se produce una gran diferencia entre el promedio de calificación entre becados y no becados. Por otro lado, en las carreras de baja demanda, las variables de nota de admisión, satisfacción con los servicios y nivel socioeconómico, sí tuvieron un impacto más marcado sobre las diferencias en el promedio entre becados y no becados. \\\n\nOtros estudios no consideran una separación entre carreras de alta y baja demanda, así como entre estudiantes becados y no becados, al estudiar los factores que pueden afectar el rendimiento académico. Por ejemplo, los estudios realizados por Izar Landeta, Ynzunza Cortés y López Gama (2011) y Montero Rojas, Villalobos Palma, y Valverde Bermúdez (2007), por lo que no es imprudente asumir que estos autores no consideran que estos factores sean tan significativos.  Las fuentes consultadas por Izar, et. al. (2007) proponen diferentes enfoques, por ejemplo: factores fisiológicos, pedagógicos, psicológicos, sociológicos, familiares, institucionales, entre otros. Basado en estos aspectos la encuesta realizada por Izar, et. al. determinó que las variables con una mayor correlación al promedio fueron el género y la intención de estudiar un posgrado, mientras que el la orientación vocacional, el nivel socioeconómico y escolaridad de los padres no mostraron mayor impacto. \\\n\nUna perspectiva distinta aun considerando los factores institucionales, pedagógicos y psicológicos como de particular importancia para el rendimiento académico, se inclina por que las variables de mayor peso son la inteligencia emocional, promedio de admisión, métodos de enseñanza y formas de evaluación. Este resultado es dado por Rojas, et al (2007) junto con la observación de que la evaluación centrada en exámenes y la enseñanza enfocada en clases magistrales tuvieron efectos negativos en el desempeño. Donde variables como la asistencia a cursos, satisfacción con la carrera, situación laboral, nivel socioeconómico fueron recopiladas por encuestas a estudiantes.\n\n### Metodología\n\nEl análisis de factores que influyen sobre el desempeño académico universitario, en especial, factores económicos, sociales, académicos y familiares, requiere de una metodología que logre segmentar el impacto de cada uno de estos factores por separado y así concluir sobre estos, así como sugerir cuáles son los que se deben considerar para investigaciones a futuro. Se implementará el uso de gráficas y tablas elaboradas en RStudio basándose en las metodologías planteadas en el libro “R for Data Science” (Grolemund, 2017) donde se proporciona un enfoque para el análisis de datos considerando la importación, limpieza y visualización de los datos utilizando el sistema tidyverse como herramienta principal. Estos pasos se caracterizan de la siguiente manera: primero, la importación de datos y la limpieza de los mismos establecen las bases para la realización de la investigación donde mediante paquetes como “readr” se carga una base de datos y se procede a implementar estructuras como “filter(), select(), mutate()”. Estos métodos permiten generar o eliminar datos según su importancia, así como clasificar información repetida para que sea más fácil su lectura. Luego mediante la herramienta “ggplot” se genera la visualización de los datos en gráficas relacionando variables que según la literatura resulta interesante de estudiar.\\\n\nPara este estudio resulta indispensable tener una base a la cual aplicar los métodos propuestos por (Grolemund, 2017), para ello se cuenta con una base de datos recolectada por Realinho (2022). Esta base cuenta con 4424 registros de estudiantes de distintas universidades europeas donde se incluyen variables continuas, discretas, binarias y otras que definen características económicas, sociales, educativas, y otras más de los estudiantes. Como resultado principal se registra la deserción del estudiante o el éxito académico proponiendo una variable “target” que cuenta con tres opciones: graduado, desertor o matriculado, que define el tipo de estudiante luego de un año de estudios. El tipo de datos que se plantean en la base de datos resulta de gran interés según Realinho (2022), debido a la riqueza y diversidad de los mismos, lo que justifica la implementación de múltiples técnicas de análisis de datos para capturar los impactos del estudio.\\\n\nEntre las técnicas que se utilizaron para relacionar las distintas variables están las siguientes. La gráfica uno trata de comparar el nivel educativo de la madre y el padre con respecto a si su hija o hijo completó sus estudios o no. La segunda gráfica, muestra si tener alguna deuda con el centro educativo impacta la decisión de desertar, esto con respecto al factor económico. Asimismo, la gráfica tres, también del área económica y además del área social busca visualizar el impacto que tienen las becas con respecto al tipo de estudiante (graduado, desertor, matriculado). La gráfica cuatro, tiene como intención identificar si el ser una persona extranjera tiene una repercusión significativa en el estudiante. El gráfico cinco toma los créditos aprobados en el primer semestre y son comparados respectivamente con el tipo de estudiante. La gráfica seis clasifica por género a las tres categorías objetivo de estudiantes. La gráfica siete amplía sobre la cinco, al incluir las notas de los primeros dos semestres. Con un enfoque distinto, el gráfico ocho evalúa el impacto de la necesidad de mudarse para asistir a la universidad. Finalmente, los gráficos nueve y diez tratan de las notas y edades de admisión, respectivamente. \n\n### Resultados\n\nEl objetivo de esta sección de resultados es presentar un desglose de los hallazgos obtenidos a partir de la metodología descrita anteriormente, la cual incluye tablas y gráficos de diferentes estilos que exploran las relaciones entre las distintas variables que ofrece la base de datos escogida. De esta manera, es posible aproximarse a una respuesta más concreta para la pregunta de investigación planteada inicialmente, es decir, la identificación de los factores sociales, económicos, académicos y familiares que tienen un mayor impacto en la trayectoria académica de un estudiante, especialmente en cuanto a la decisión de concluir los estudios universitarios o abandonarlos. También, se busca comparar y contrastar los resultados propios de este estudio con los argumentos propuestos por los autores citados a lo largo del trabajo, para así contribuir al conocimiento general del tema e incluso hallar vacíos en la literatura existente.\\\n\nEl primer resultado parte del Gráfico #1 y trata de la relación entre la completitud de los estudios superiores de ambos padres y la permanencia del estudiante en la carrera. Al observar el gráfico, se nota que la diferencia en la cantidad de estudiantes cuyos padres son ambos graduados universitarios entre los desertores y matriculados es muy poca. Esto contradice la suposición que entre mayor es el nivel educativo de los padres, sus hijos van a tener uno igual o mayor. Sin embargo, esta relación a primera vista un poco contradictoria es respaldada por la literatura en el artículo de Landeta et al (2011). Además, este resultado también es observado para aquellos estudiantes cuyos padres (tanto madre como padre) no han completado la educación primaria, ya que esta combinación es la más frecuente para ambos desertores y graduados. En pocas palabras, la diferencia en el número de estudiantes que deciden desertar y aquellos graduados, cuyos padres ambos poseen títulos universitarios es muy poca y dada la gran cantidad de combinaciones entre el nivel educativo del padre y la madre se dificulta establecer una única conclusión global.\\\n\nEl segundo resultado se obtiene del Gráfico #2, el cual aborda la relación entre el cumplimiento de las cuotas escolares y la permanencia del estudiante en la carrera. Al plantear un gráfico de barras que muestra si un estudiante es deudor en cuotas escolares según su categoría (desertor, graduado o matriculado) se revela una fuerte tendencia. En los estudiantes graduados, ninguno o casi ninguno es deudor de cuotas escolares, lo cual es esperable dado que ya concluyeron sus estudios. Asimismo, es posible que la puntualidad de los pagos sea un requisito para los estudiantes matriculados. Sin embargo, lo más relevante es que en los estudiantes desertores existe una parte significativa de la población que es deudora, lo que muestra que la imposibilidad de pagar las cuotas escolares por dificultades económicas puede ser un factor de peso en la decisión de abandonar la carrera. Este hallazgo es consistente con Lobos Rivera y Rodríguez Vásquez (2023).\\\n\nComo tercer resultado está el impacto de la obtención de una beca socioeconómica en la permanencia en la universidad, analizado mediante el Gráfico #3. Esta gráfica de tipo heatmap muestra la frecuencia absoluta de cada combinación de las dos variables categóricas escogidas: tipo de estudiante y si es poseedor de beca. La conclusión es clara, pues dentro del grupo de los estudiantes poseedores de beca, los estudiantes graduados son los más numerosos, mientras que en los estudiantes sin beca, la diferencia entre las tres categorías no es tan significativa. Nuevamente se puede deducir que  la situación económica que enfrenta cada estudiante tiene un gran impacto en su decisión de continuar con su carrera universitaria o no. Esta relación es recurrente en el material bibliográfico y ha sido estudiada en títulos como el de Sistemas Ecológicos de Urie Bronfenbrenner.\\\n\nLa independencia entre el origen del estudiante y la permanencia en la carrera es el cuarto resultado encontrado a través de los gráficos. El Gráfico #4, generado a partir de las frecuencias obtenidas de clasificar los estudiantes según su categoría (desertor, graduado o matriculado) y separarlos con una variable binaria (internacional o no), demuestra que no existe una relación contundente entre la permanencia del estudiante en la carrera y si es internacional. Los estudiantes internacionales siguen la misma tendencia general que los estudiantes no internacionales, solo que a una escala mucho menor. Es decir, en ambos grupos existen más graduados que desertores y más desertores que matriculados, por lo que la diferencia entre internacional y no internacional no es relevante. Además, se reconoce que podría ser más apropiado utilizar frecuencias relativas y no absolutas, así como el hecho de que agrupar todas las nacionalidades extranjeras en una única categoría enmascara comportamientos particulares de cada una que podrían ser útiles si se estudiaran por separado.\\\n\nOtro resultado de carácter académico es la relación entre los créditos aprobados en el primer semestre de educación universitaria y la permanencia en la carrera, derivado del Gráfico #5. Al visualizar la densidad de los créditos aprobados en el primer semestre por categoría de estudiante se evidencian patrones claros sobre el impacto de las primeras evaluaciones universitarias en el estudiante. Primero, los estudiantes con pocos créditos aprobados en el primer semestre son más propensos a ser desertores. De hecho, la mayor densidad de desertores ocurre cuando no se aprobó ningún crédito. Por otro lado, la máxima densidad de estudiantes graduados se da en un valor de créditos aprobados más elevado. Esto insinúa que existe una relación positiva entre créditos aprobados en primer semestre y la posibilidad de graduarse. Por lo tanto, las primeras experiencias con la evaluación universitaria son importantes para las decisiones del estudiante. No obstante, puede que sea necesario evaluar créditos aprobados contra créditos matriculados, pues la proporción entre estas variables es más representativa del “éxito” en el primer semestre que la cantidad absoluta de créditos aprobados.\\\n\nOtra forma de estudiar las diferencias entre las notas de estudiantes graduados, desertores y matriculados es mediante la Tabla #4. Esta tabla emplea medidas estadísticas de tendencia central para determinar que los estudiantes graduados presentan una media de notas en el primer semestre significativamente mayor que los desertores y matriculados, lo que coincide con lo mostrado visualmente por el Gráfico #5. Sin embargo, hay una amplia variabilidad en las notas, especialmente entre los graduados, quienes presentan una desviación estándar relativamente alta en comparación a su media y mediana, lo cual sugiere que existen algunos impactos complementarios que afectan el desempeño. Por otro lado, los datos de los estudiantes matriculados son los que se mantienen más consistentes.\\\n\nA manera de sexto resultado, el Gráfico #6 se enfoca en la relación significativa entre el género de los estudiantes y su permanencia en la carrera. En este gráfico de barras segmentado se observan dos variables categóricas: el género y el tipo de estudiante, lo cual permitió apreciar que la cantidad de estudiantes mujeres graduadas es significativamente mayor a la cantidad de estudiantes hombres graduados. Según la investigación realizada por Landeta, et al (2011) una de las variables con mayor influencia en el rendimiento académico probó ser el género, siendo las mujeres aquellas con un rendimiento académico mayor en comparación de sus compañeros hombres, lo que encaja con este gráfico. Sin embargo, es importante notar que no hay una diferencia significativa entre géneros dentro de la categoría de desertor. Otra consideración pertinente es que al tomar en cuenta sólo dos géneros, existe una parte de la población que queda totalmente fuera del estudio, pero este problema viene desde el origen de los datos.\\\n\nDe forma complementaria, la Tabla #5 respalda el resultado argumentado en el Gráfico #6, pero empleando un método cuantitativo que incluye frecuencias absolutas y medidas de tendencia central. Con esta tabla, que considera el promedio ponderado total por semestre de los estudiantes, tanto graduados, como desertores y matriculados, fue posible reafirmar la conclusión de que las estudiantes del género femenino presentan una media de notas más alta que los estudiantes masculinos en un año lectivo. Sin embargo, el grupo femenino presenta una mayor desviación estándar, lo cual puede distorsionar la aplicabilidad de este resultado. Las desviaciones de los estudiantes masculinos son significativamente inferiores que las de las estudiantes femeninas, significando así que se tiene un registro más consistente en sus notas. Note que además no se está separando la información según el tipo de estudiante y dado que hay más estudiantes femeninos graduados que masculinos esto justifica muy bien la diferencia entre estas características.\\\n\nEl resultado siete proporciona información sobre el vínculo entre las notas del primer año y la decisión de continuar sus estudios superiores o desertar. Mientras que el Gráfico #5 era de tipo densidad y sólo consideraba las notas del primer semestre, el Gráfico #7 profundiza en esta idea y utiliza una representación scatter para asociar las notas de los primeros dos semestres y la categoría del estudiante. Basado en este gráfico, es posible concluir que los estudiantes con notas más altas durante tanto el primer como el segundo semestre son aquellos que con mayor frecuencia se gradúan. Es decir, aquellos estudiantes con notas más bajas son más propensos a abandonar la educación superior.  Esta tendencia, de mejores notas en las personas que eventualmente se gradúan se expone tanto por Martinez-Otero (2009), como por Lobos y Rodriguez (2022). Aunque la importancia que ambos textos le dan a este factor varía, ambos están de acuerdo en que el rendimiento académico si forma parte de la decisión que es desertar.\\\n\nEl octavo resultado describe la incidencia sobre la permanencia en la carrera de la necesidad de desplazamiento a la universidad, extraído del Gráfico #8. Agrupando los estudiantes entre aquellos que tuvieron que desplazarse para asistir a la universidad y los que no, luego clasificándolos por su estado en la carrera (graduado, matriculado o desertor) y representando estos datos en un gráfico facetado de tipo treemap, se revelaron comportamientos interesantes. Primero, es destacable que entre los desplazados existe una menor cantidad de desertores que en los no desplazados, aunque en términos absolutos existen más estudiantes del primer grupo que del segundo. Otro resultado llamativo es que, dentro de los desplazados, la categoría de estudiantes graduados representan alrededor del 54,57%, mientras que en los no desplazados, los graduados componen el 44,29%. Lo anterior parece indicar que existe una mayor probabilidad de graduarse entre los estudiantes que tuvieron que mudarse para recibir una educación superior. Esto contradice los resultados de Lobos y Rodríguez (2022), quienes argumentan que los costos de alquiler y transporte son algunos de los principales obstáculos que enfrentan los estudiantes para continuar con su carrera.\\\n\nPara el noveno resultado, se presenta la importancia de la nota de admisión sobre la probabilidad de que un estudiante se gradúe, la cual fue identificada en el Gráfico #9. Al graficar la distribución de las notas de admisión según la categoría final del estudiante mediante un diagrama de cajas, se obtuvo un resultado previsible, aunque tal vez la tendencia no es tan fuerte como se esperaba. Es evidente que el valor de la mediana para los estudiantes graduados es mayor que el de los demás grupos. Además, en el tercer cuartil de la categoría de graduados están contenidos valores más altos que en las otras dos. Estos resultados concuerdan con los hallazgos de Montero, Villalobos y Valverde (2007), que determinaron que el promedio de admisión tiene una relación positiva con el desempeño académico más adelante en la carrera. Sin embargo, la similitud de los “bigotes” entre las tres clasificaciones, lo cual indica una variabilidad similar de los valores en los tres grupos, así como la presencia de valores atípicos muy altos entre los desertores, hacen cuestionar la firmeza de esta tendencia.\\\n\nEl resultado que ofrece el Gráfico #10 es de tipo social, pues muestra la influencia de la edad de ingreso a la universidad sobre la permanencia en la carrera. La representación mediante un gráfico tipo ridgeline de la densidad de las edades de admisión a la universidad según la categoría del estudiante reveló tendencias significativas. Un resultado predecible es el hecho de que en todos los grupos, la mayor densidad ocurre entre los 18 y los 20 años, lo cual no es sorprendente dado que una gran cantidad de los estudiantes que ingresan a las universidades acaban de concluir los estudios secundarios. Más interesante es la distribución de la densidad del grupo de desertores, que son la categoría con mayor densidad después de los 25 años y los únicos con una densidad apreciable más allá de los 42 años. Por el contrario, la gran mayoría de los estudiantes graduados o matriculados entraron a la universidad con menos de 25 años. Lejos de una cuestión meramente etaria, estas tendencias pueden ser resultado de factores socioeconómicos, ya que es posible que los estudiantes que ingresan a una edad más avanzada se vean obligados a abandonar los estudios por responsabilidades laborales o familiares, razones que resalta Estrada-Ruiz (2015), especialmente en mujeres. Por otro lado, los estudiantes más jóvenes probablemente carecen de estas obligaciones y hasta reciben apoyo de sus familiares.\\\n\nFinalmente, la tabla 5 brinda resultados sobre los cursos con mayor asistencia, así como la cantidad de estudiantes que acabaron matriculados, graduados o desertando. Podemos observar que los cursos con mayor cantidad de estudiantes matriculados son enfermería y administración siendo este último el de mayor porcentaje de deserción. Se observa que los cursos con mayor cantidad de personas graduadas son enfermería y servicio social mientras que además de administración es en el área de enfermería y comunicación donde se encuentra la mayor deserción estudiantil. \n\n## Parte de reflexión\n\nBasado en las metodologías empleadas y los resultados obtenidos hasta el momento, se propone la siguiente versión actualizada de la UVE de Gowin:\n\n![UVE Actualizada](/Images/UVE_Actualizada.png)\n\n### Correcciones y mejoras desde la bitácora anterior:\n- Descripción para cada gráfica y tabla. \\\n- Captions con la fuente y autoría de cada gráfico y tabla. \\\n- Metodología correcta en UVE de Gowin. \\\n\n \n# Changelog\n\nAll notable changes to this project will be documented in this file.\n\n## [unreleased]\n\n### 🚀 Features\n\n- Actualiza el sitio con correcciones\n- Añadi imagenes\n- Imágenes en carpeta\n- Actualiza la bitácora 1 a versión final\n- Agregar Bitacora 2\n- Agrega archivo .R\n- Cambio de Rama\n- Añade paquetes y 3 gráficos\n- Agrega Base de Datos\n- Grafico de nivel educativo padres y educacion del estudiante\n- Grafico estudiantes y permanencia\n- Esqueleto bitacora 2\n- Pegar resumenes y intento tabla\n- Fichas de 3-10\n- Gráfica nueva\n- Merge\n- Resuelve conflicto\n- Gráfico Nacionalidad-Nota\n- Arreglos Git\n- Arreglos y Cambios realizados\n- Intento de subir gráficas\n- Contrastes y tabla literaria\n- Añade Gráficas y Arregal Estructura Quarto\n- Formato\n- Correccion tabla\n- Fichas resultado\n- Estructura quarto\n- Tabla nueva\n- Tabla Nueva Arreglada\n- Tabla nueva\n- Agrega nombres de autores a resúmenes\n- Ageregar espacios en fichas\n- Agrega enlaces de literatura\n- Añade Gráficas\n- Añade otra gráfica\n- Nuevas Gráficas\n- Grafica extra\n- Cambios en conflictos\n- Anadir files\n- Añade presentación\n- Presentacion\n- Formato\n- Formato\n- Arregla quarto\n- Errores\n- Resuelve conflicto bitácora 2\n- Bitacora 3\n- Anadir bit-3\n- Correcciones bit-2\n- Primeros 2 graficos y fichas\n- Bit-3\n- Bit 2\n- Arregla conflictos\n- Conflictos\n- Añade gráficas\n- Resuelve conflictos\n- Grafica uno\n- Cambios generales\n- Grafica uno\n- Añade cita de Montero\n- Grafica dos y tres\n- Grafica cuatro y cinco\n- Graficas y tablas\n- Graficas y tablas\n- Logs.txt\n- Describe gráficas 1 y 2\n- Describe gráficas 3 y 4\n- Describe gráficas 5 y 6\n- Describe gráficas 7 y 8\n- Describe gráficas 9 y 10\n- Agrega descripción de tablas\n- Agrega tabla de elementos de reporte\n- Agrega tabla ordenada de elementos de reporte\n- Agrega intro a parte de escritura\n- Agrega metodología a parte de escritura\n- Agrega y corrige fichas de resultados\n- Agrega ficha 9\n- Agrega ficha 10\n- Agrega ficha 11\n- Agrega ficha 12\n- Agrega ficha 13\n- Añade resultados a sección de escritura\n- Coreccion codigo\n- Cambio idioma\n- Agrega UVE actualizada\n- Uve\n- Correcciones nombre\n- Agrega sección de cambios y mejoras\n- Correciones fichas\n\n### 🐛 Bug Fixes\n\n- Arreglos\n- Resuelve Conflicto\n- Formato\n- Tamano grafico\n- Graficas\n- Arregla Conflicto\n- Arreglos tabla\n- Arregla Estructura de Todo\n- Arregla estructura\n- Conflictos\n- Tabla y grafica\n- Merge\n- Formato fichas\n- Merge\n- Conflictos\n- Arreglo pagina\n- Arreglar pagina\n- Pagina\n- Cambio en numeracion\n- Arreglo conflicto\n\n### ⚙️ Miscellaneous Tasks\n\n- Cambios en bitácora\n- Actualiza sitio\n- Corrige código\n\n## [Bitacora-1] - 2024-09-05\n\n### 🚀 Features\n\n- Agrega documento\n- Agrega proyecto de R\n- Agrega archivo del índice\n- Agrega archivo de referencias\n- Prueba\n- Agrega nombres\n- Borrar pruebas\n- Titulos añadidos\n- Algunas definiciones añadidas\n- Molde para argumentacion de la pregunta\n- Agregué Tensiones\n- Pregunta #2\n- Formato Reformulación Pregunta\n- Referencia y Ficha de Literatura\n- Introducción al Análisis de Datos\n- Intento de Arreglo de errores\n- Bibliografía nueva\n- Añadi definicion de la idea\n- Bibliografía nueva\n- Bibliografía nueva\n- Arreglo\n- Arreglos a bitácora\n- Añadi conceptos\n- Añadi una tension\n- Añadi las 4 preguntas\n- Merge\n- Bibliografía nueva\n- Preguntas añadidas en seccion respectiva\n- Tension 2 y 3\n- Añadi nombre y seccion de teorias\n- Arreglo bibliografía\n- Errores en url referencias\n- Bibliografía Urie Bronfenbrenner\n- Error en commits\n- Actualiza el sitio web\n- Agrega imagen de la UVE al sitio\n- Agrega contraargumentos de primera pregunta\n- Agrega argumentos de primera pregunta\n- Agrega contraargumentos de segunda pregunta\n- Añade contraargumentos de tercera pregunta\n- Añade argumentos de tercera pregunta\n- Agrega contraargumentos de cuarta pregunta\n- Incorpora argumentos de la cuarta pregunta\n- Agrega ficha de literatura 1\n- Agrega ficha de literatura 2\n- Agrega argumentos de la segunda pregunta\n- Añade las conclusiones de la argumentación de cada pregunta\n- Añadi primera teoria\n- Añadi segunda teoria\n- Agrega Bibliografía\n- Añadi parte datos\n- Añadi Datos\n- Añadi ficha 3\n- Añadi referencias\n- Añadi citas en fichas\n- Añade referencias base de datos\n- Añadi prregunta investigacion y subtitulo\n- Agrega primera parte del resumen\n- Segunda parte de resumen\n- Parte final del resumen\n- Añadi introduccion\n- Correccion introduccion\n- Correcion introduciion (2)\n- Correcion cita en resumen\n- Actualiza el contenido del sitio\n- Actualiza los contenidos del sitio\n\n### 🐛 Bug Fixes\n\n- Cambiar nombre de la carpeta a docs\n- Coreccion error doc\n- Elimina carpeta doc duplicada\n- Borrar pruebas\n- Tildes\n- Error en Formato\n- Correcciones formato preguntas\n- Correcciones formato\n- Arreglos al Quarto\n- Cambio de Base de Datos\n- Arreglar formato\n- Eliminar Sección\n- Correccion parentesis\n- Correccion formato titulos\n- Coreccion nombre de seccion introduccion\n- Mejoras formato (area fichas literatura)\n- Arreglo cita factor_académico\n- Formato teorias o principios\n- Error bibliografía\n- Errores en el url\n- Formato conceptos\n- Corrección de enlace del repositorio\n- Agrega source a repo-actions\n- Arreglé error references.bib\n- Corrección Formato\n- Arregle Cambios\n- Arregla conflicto\n- Corregi cita\n- Arregla menciones de la referencias\n- Formato cita en teoria 2\n- Correccion escritura de definicion\n- Coreccion de errores ortograficos y redaccion\n- Correcciones formato\n\n### ⚙️ Miscellaneous Tasks\n\n- Agrega configuración de pre-commit\n- Actualiza sitio\n- Agrega archivo de formato de quarto\n- Argumentación pregunta 2\n- Formato e Introducción del Análisis de Datos\n- Carpeta para imágenes\n- Arreglar formato documento\n- Error\n- Eliminar chapter referencias\n- Modifica gitignore para incluir docs\n- Actualiza el sitio web\n- Actualiza el sitio web posterior a nuevo render\n\n<!-- generated by git-cliff -->\n\n# Gitlog\n\n2a36c2f (2024-10-30, 01:50) [Debbie Con] (HEAD -> main, origin/main, origin/HEAD) feat: correciones fichas\n77f9c55 (2024-10-30, 01:49) [Debbie Con] feat: correcciones nombre\n 13 files changed, 19 insertions(+), 12 deletions(-)\n\n743bbdf (2024-10-30, 01:45) [Aaron Retana] feat: agrega sección de cambios y mejoras\n 2 files changed, 6 insertions(+), 1 deletion(-)\n\n401ca48 (2024-10-30, 01:33) [Debbie Con] feat: uve\n06faa00 (2024-10-30, 01:32) [Debbie Con] feat: cambio idioma\n 4 files changed, 362 insertions(+), 89 deletions(-)\n\na24d63a (2024-10-30, 01:31) [Aaron Retana] feat: agrega UVE actualizada\n 1 file changed, 5 insertions(+), 1 deletion(-)\n\nf3b34a9 (2024-10-30, 01:24) [Debbie Con] feat: coreccion codigo\nadfc7b5 (2024-10-30, 01:23) [Debbie Con] feat: logs.txt\n 3 files changed, 788 insertions(+), 18 deletions(-)\n\nd745485 (2024-10-30, 01:21) [Aaron Retana] feat: añade resultados a sección de escritura\n 1 file changed, 29 insertions(+)\n\na0e5214 (2024-10-30, 01:12) [Aaron Retana] feat: agrega ficha 13\n 1 file changed, 12 insertions(+)\n\n2bbd3f5 (2024-10-30, 01:09) [Aaron Retana] feat: agrega ficha 12\n 1 file changed, 13 insertions(+), 1 deletion(-)\n\n3d6cc60 (2024-10-30, 01:06) [Aaron Retana] feat: agrega ficha 11\n 1 file changed, 12 insertions(+), 1 deletion(-)\n\n23d6ad0 (2024-10-30, 01:02) [Aaron Retana] feat: agrega ficha 10\n 1 file changed, 13 insertions(+)\n\nf13ce81 (2024-10-30, 01:00) [Aaron Retana] feat: agrega ficha 9\n 1 file changed, 13 insertions(+), 1 deletion(-)\n\n38d0695 (2024-10-30, 00:57) [Aaron Retana] feat: agrega y corrige fichas de resultados\n 1 file changed, 16 insertions(+), 5 deletions(-)\n\na9b1fe1 (2024-10-30, 00:50) [Aaron Retana] feat: agrega metodología a parte de escritura\n 1 file changed, 8 insertions(+)\n\n1973713 (2024-10-30, 00:49) [Aaron Retana] feat: agrega intro a parte de escritura\n 1 file changed, 20 insertions(+)\n\n088f938 (2024-10-30, 00:45) [Aaron Retana] feat: agrega tabla ordenada de elementos de reporte\n 1 file changed, 9 insertions(+), 1 deletion(-)\n\ncdb60a1 (2024-10-30, 00:39) [Aaron Retana] feat: agrega tabla de elementos de reporte\n 1 file changed, 17 insertions(+)\n\n8cc9b25 (2024-10-30, 00:22) [Aaron Retana] feat: agrega descripción de tablas\n 1 file changed, 10 insertions(+), 3 deletions(-)\n\n8877b0b (2024-10-30, 00:20) [Aaron Retana] feat: describe gráficas 9 y 10\n 1 file changed, 6 insertions(+), 2 deletions(-)\n\n922c08a (2024-10-30, 00:18) [Aaron Retana] feat: describe gráficas 7 y 8\n 1 file changed, 6 insertions(+), 2 deletions(-)\n\na4a4e4a (2024-10-30, 00:16) [Aaron Retana] feat: describe gráficas 5 y 6\n 1 file changed, 5 insertions(+), 2 deletions(-)\n\n8fb56d2 (2024-10-30, 00:14) [Aaron Retana] feat: describe gráficas 3 y 4\n 1 file changed, 2 insertions(+), 3 deletions(-)\n\n555e545 (2024-10-30, 00:12) [Aaron Retana] feat: describe gráficas 1 y 2\n 1 file changed, 4 insertions(+), 2 deletions(-)\n\n1549e7d (2024-10-30, 00:08) [Debbie Con] feat: graficas y tablas\n 4 files changed, 44 insertions(+), 34 deletions(-)\n\n8aa825a (2024-10-30, 00:03) [Debbie Con] feat: graficas y tablas\n 19 files changed, 567 insertions(+), 65 deletions(-)\n\n088ae4d (2024-10-29, 23:37) [Debbie Con] feat: grafica cuatro y cinco\n 16 files changed, 184 insertions(+), 67 deletions(-)\n\nd7451d3 (2024-10-29, 23:27) [Debbie Con] feat: grafica dos y tres\n 35 files changed, 7872 insertions(+), 82 deletions(-)\n\n6c613ca (2024-10-29, 23:21) [Andrey Prado] feat: añade cita de Montero\n 60 files changed, 3 insertions(+), 6150 deletions(-)\n\n52480b5 (2024-10-29, 23:16) [Debbie Con] feat: grafica uno\n1c3d358 (2024-10-29, 23:15) [Debbie Con] feat: grafica uno\n 61 files changed, 6603 insertions(+), 68 deletions(-)\n\n4c06886 (2024-10-29, 22:24) [Andrey Prado] feat: cambios generales\n 38 files changed, 138 insertions(+), 901 deletions(-)\n\n3bcf371 (2024-10-29, 20:43) [Debbie Con] fix: arreglo conflicto\n491e5f1 (2024-10-29, 20:40) [Debbie Con] feat: bit 2\n 1 file changed, 2 insertions(+), 9 deletions(-)\n\n97e26cf (2024-10-29, 20:37) [Andrey Prado] feat: resuelve conflictos\n037b544 (2024-10-29, 20:34) [Andrey Prado] feat: añade gráficas\n 88 files changed, 48 insertions(+), 10001 deletions(-)\n\ndeab991 (2024-10-29, 20:32) [Debbie Con] fix: cambio en numeracion\n 3 files changed, 5 insertions(+), 5 deletions(-)\n\ncaf6e85 (2024-10-29, 14:38) [Andrey Prado] feat: conflictos\n14421e2 (2024-10-29, 14:34) [Andrey Prado] feat: arregla conflictos\n 39 files changed, 225 insertions(+), 491 deletions(-)\n\n556348c (2024-10-29, 02:15) [Debbie Con] feat: bit-3\n 1 file changed, 518 deletions(-)\n\n4ff0a74 (2024-10-29, 02:14) [Debbie Con] feat: primeros 2 graficos y fichas\n 20 files changed, 4170 insertions(+)\n\nea33de1 (2024-10-29, 02:12) [Debbie Con] feat: correcciones bit-2\n 20 files changed, 44 insertions(+), 26 deletions(-)\n\nbf3e022 (2024-10-29, 02:11) [Debbie Con] feat: anadir bit-3\n 1 file changed, 1 insertion(+)\n\nced36ad (2024-10-28, 20:00) [Debbie Con] feat: bitacora 3\n 15 files changed, 3771 insertions(+), 15 deletions(-)\n\n3085249 (2024-10-28, 19:40) [Debbie Con] fix: pagina\n9480394 (2024-10-28, 19:37) [Debbie Con] fix: arreglar pagina\n 1 file changed, 0 insertions(+), 0 deletions(-)\n\na5f4316 (2024-10-28, 19:36) [Debbie Con] fix: arreglo pagina\n 23 files changed, 260 insertions(+), 451 deletions(-)\n\n70b89f7 (2024-10-28, 11:48) [Aaron Retana] chore: corrige código\n 4 files changed, 84 insertions(+), 101 deletions(-)\n\nd15c35d (2024-10-28, 11:35) [Aaron Retana] chore: actualiza sitio\n 22 files changed, 191 insertions(+), 438 deletions(-)\n\nc6e59d4 (2024-10-27, 17:21) [Debbie Con] fix: conflictos\n81767de (2024-10-27, 17:16) [Debbie Con] feat: formato\n 1 file changed, 38 insertions(+), 27 deletions(-)\n\ncd45756 (2024-10-27, 17:16) [Debbie Con] feat: formato\n 1 file changed, 1 insertion(+), 1 deletion(-)\n\n481ccc0 (2024-10-27, 15:46) [Andrey Prado] feat: resuelve conflicto bitácora 2\nf98a4da (2024-10-27, 15:42) [Andrey Prado] feat: errores\n 128 files changed, 6581 insertions(+), 396 deletions(-)\n\nb9a4aa3 (2024-10-27, 15:24) [Andrey Prado] feat: arregla quarto\n 4 files changed, 243 insertions(+), 104 deletions(-)\n\nd520b29 (2024-10-25, 18:14) [Debbie Con] fix: merge\n 5 files changed, 876 insertions(+), 328 deletions(-)\n\n9054933 (2024-10-25, 18:09) [Debbie Con] feat: presentacion\n9987449 (2024-10-24, 16:09) [Debbie Con] feat: anadir files\n7d2edc8 (2024-10-03, 09:13) [Andrey Prado] feat: Añade presentación\n 1 file changed, 165 insertions(+)\n\n0b57ea2 (2024-10-02, 20:49) [Andrey Prado] feat: cambios en conflictos\n1154b84 (2024-10-02, 20:43) [Debbie Con] fix: formato fichas\n 2 files changed, 91 insertions(+), 57 deletions(-)\n\n7148e89 (2024-10-02, 20:38) [Andrey Prado] feat: grafica extra\n 17 files changed, 9 insertions(+), 9 deletions(-)\n\nf88b855 (2024-10-02, 20:37) [Andrey Prado] feat: Nuevas Gráficas\n 15 files changed, 12 insertions(+), 7 deletions(-)\n\n2f7db99 (2024-10-02, 20:29) [Debbie Con] fix: merge\nb221a6c (2024-10-02, 20:29) [Debbie Con] feat: ageregar espacios en fichas\n 3 files changed, 207 insertions(+), 1626 deletions(-)\n\nea717bb (2024-10-02, 20:27) [Aaron Retana] feat: agrega enlaces de literatura\n 3 files changed, 45 insertions(+), 2 deletions(-)\n\na868108 (2024-10-02, 20:17) [Andrey Prado] feat: Añade otra gráfica\n 9 files changed, 369 insertions(+), 301 deletions(-)\n\na212003 (2024-10-02, 20:16) [Andrey Prado] feat: Añade Gráficas\n 9 files changed, 213 insertions(+), 85 deletions(-)\n\ndbf773f (2024-10-02, 20:13) [Aaron Retana] feat: agrega nombres de autores a resúmenes\n 3 files changed, 445 insertions(+), 147 deletions(-)\n\n88ab30c (2024-10-02, 20:02) [Debbie Con] fix: tabla y grafica\n80ee2db (2024-10-02, 19:56) [Debbie Con] fix: arreglos tabla\n 2 files changed, 16 insertions(+), 8 deletions(-)\n\n0673769 (2024-10-02, 19:39) [Andrey Prado] feat: Tabla nueva\n 4 files changed, 92 insertions(+), 40 deletions(-)\n\nc854795 (2024-10-02, 19:27) [Andrey Prado] feat: Tabla Nueva Arreglada\n7eb0163 (2024-10-02, 19:23) [Andrey Prado] feat: tabla nueva\n 1 file changed, 57 insertions(+), 2 deletions(-)\n\nc81ceea (2024-10-02, 19:02) [Debbie Con] feat: fichas resultado\n 1 file changed, 39 insertions(+)\n\n4274932 (2024-10-02, 18:49) [Andrey Prado] feat: Estructura quarto\nffc03e0 (2024-10-02, 18:48) [Andrey Prado] fix: conflictos\n66bf831 (2024-10-02, 18:46) [Debbie Con] feat: correccion tabla\n 1 file changed, 3 insertions(+), 2 deletions(-)\n\nf08a105 (2024-10-02, 18:38) [Andrey Prado] fix: arregla estructura\n 37 files changed, 21 insertions(+), 6523 deletions(-)\n\n5dccc15 (2024-10-02, 18:31) [Andrey Prado] fix: Arregla Estructura de Todo\n 1 file changed, 14 insertions(+), 35 deletions(-)\n\n3250d4e (2024-10-02, 18:30) [Debbie Con] feat: formato\n4a9398d (2024-10-02, 18:05) [Debbie Con] feat: contrastes y tabla literaria\naefe3dd (2024-10-02, 17:52) [Andrey Prado] feat: Añade Gráficas y Arregal Estructura Quarto\n 2 files changed, 31 insertions(+), 125 deletions(-)\n\n2580172 (2024-10-02, 14:39) [Debbie Con] fix: graficas\n 2 files changed, 166 insertions(+), 39 deletions(-)\n\n4ba62a8 (2024-10-02, 14:25) [Debbie Con] fix: tamano grafico\n 1 file changed, 18 insertions(+), 5 deletions(-)\n\n9630071 (2024-10-02, 11:57) [Andrey Prado] feat: intento de subir gráficas\n 2 files changed, 426 insertions(+), 32 deletions(-)\n\n8f48b5b (2024-10-02, 10:57) [Andrey Prado] feat: Arreglos y Cambios realizados\n 2 files changed, 19 insertions(+), 9 deletions(-)\n\n8f22f04 (2024-10-02, 10:38) [Andrey Prado] feat: Arreglos Git\n39cac65 (2024-10-02, 10:25) [Andrey Prado] fix: Arregla Conflicto\n7c9d29c (2024-10-02, 01:18) [Debbie Con] feat: fichas de 3-10\n 1 file changed, 178 insertions(+)\n\n82b1601 (2024-10-02, 00:34) [Debbie Con] feat: pegar resumenes y intento tabla\n 1 file changed, 49 insertions(+), 7 deletions(-)\n\n56a034c (2024-10-01, 22:51) [Debbie Con] feat: esqueleto bitacora 2\n 3 files changed, 132 insertions(+), 102 deletions(-)\n\n1808bb3 (2024-10-01, 20:45) [Andrey Prado] feat: Gráfico Nacionalidad-Nota\n 1 file changed, 40 insertions(+)\n\n8cf23eb (2024-10-01, 20:12) [Andrey Prado] feat: resuelve conflicto\n146ec89 (2024-10-01, 20:09) [Andrey Prado] chore: Cambios en bitácora\n 5 files changed, 22 insertions(+)\n\n55a7805 (2024-10-01, 18:03) [Andrey Prado] feat: Merge\n 1 file changed, 4 insertions(+), 1 deletion(-)\n\n39b3c68 (2024-09-30, 23:53) [Debbie Con] feat: grafico estudiantes y permanencia\n 1 file changed, 248 insertions(+), 6 deletions(-)\n\na42f45f (2024-09-30, 22:48) [Andrey Prado] feat: Gráfica nueva\n 2 files changed, 78 insertions(+), 3 deletions(-)\n\n96281f6 (2024-09-30, 22:29) [Debbie Con] feat: grafico de nivel educativo padres y educacion del estudiante\n 1 file changed, 2 insertions(+), 2 deletions(-)\n\naade898 (2024-09-30, 22:09) [Debbie Con] fix: formato\n46f0cb5 (2024-09-30, 10:33) [Debbie Con] fix: arreglos\n 1 file changed, 3 insertions(+)\n\n856fe0e (2024-09-30, 10:26) [Andrey Prado] feat: Agrega Base de Datos\n 1 file changed, 4425 insertions(+)\n\ndb8636e (2024-09-26, 19:17) [Andrey Prado] fix: Resuelve Conflicto\n2e32922 (2024-09-26, 19:14) [Andrey Prado] feat: Añade paquetes y 3 gráficos\n 1 file changed, 131 insertions(+)\n\ndec3d4d (2024-09-26, 17:47) [Andrey Prado] feat: Cambio de Rama\n 18 files changed, 655 insertions(+), 644 deletions(-)\n\n998b383 (2024-09-26, 17:42) [Andrey Prado] feat: Agrega archivo .R\n 2 files changed, 36 insertions(+), 2 deletions(-)\n\n286943a (2024-09-16, 21:09) [Andrey Prado] feat: Agregar Bitacora 2\n 2 files changed, 9 insertions(+)\n\n8105336 (2024-09-04, 23:00) [Aaron Retana] feat: actualiza la bitácora 1 a versión final\n 2 files changed, 12 insertions(+), 4 deletions(-)\n\n872bfc2 (2024-09-04, 22:57) [Andrey Prado] feat: imágenes en carpeta\n 31 files changed, 0 insertions(+), 0 deletions(-)\n\n64f0c27 (2024-09-04, 22:51) [Andrey Prado] feat: añadi imagenes\n 1 file changed, 14 insertions(+), 1 deletion(-)\n\n4f85a49 (2024-09-04, 22:16) [Aaron Retana] feat: actualiza el sitio con correcciones\n 3 files changed, 161 insertions(+), 69 deletions(-)\n\n44614d2 (2024-09-04, 22:03) [Debbie Con] (tag: vBitacora-1) fix: correcciones formato\n 1 file changed, 75 insertions(+), 93 deletions(-)\n\n5a8e679 (2024-09-04, 22:00) [Debbie Con] fix: coreccion de errores ortograficos y redaccion\n 1 file changed, 8 insertions(+), 8 deletions(-)\n\n01c8049 (2024-09-04, 20:28) [Debbie Con] fix: correccion escritura de definicion\n6399d3b (2024-09-04, 20:16) [Debbie Con] feat: correcion cita en resumen\n 1 file changed, 1 insertion(+), 1 deletion(-)\n\nc05e2e3 (2024-09-04, 20:12) [Aaron Retana] feat: actualiza los contenidos del sitio\n 2 files changed, 7 insertions(+), 7 deletions(-)\n\nbc250ed (2024-09-04, 20:11) [Aaron Retana] feat: actualiza el contenido del sitio\n 3 files changed, 121 insertions(+), 32 deletions(-)\n\n53a05b6 (2024-09-04, 20:08) [Debbie Con] fix: formato cita en teoria 2\n 1 file changed, 1 insertion(+), 1 deletion(-)\n\n94c35fe (2024-09-04, 20:04) [Debbie Con] feat: correcion introduciion (2)\n 1 file changed, 1 insertion(+)\n\n80742fd (2024-09-04, 20:03) [Debbie Con] feat: correccion introduccion\n 1 file changed, 1 insertion(+)\n\n9a6cc69 (2024-09-04, 20:02) [Debbie Con] feat: añadi introduccion\n 1 file changed, 2 insertions(+)\n\n09fab70 (2024-09-04, 19:48) [Aaron Retana] fix: arregla menciones de la referencias\n 1 file changed, 13 insertions(+), 13 deletions(-)\n\n1fe7e3d (2024-09-04, 19:36) [Aaron Retana] feat: parte final del resumen\n 1 file changed, 34 insertions(+)\n\nb09cb11 (2024-09-04, 19:33) [Aaron Retana] feat: segunda parte de resumen\n 1 file changed, 36 insertions(+)\n\n3989672 (2024-09-04, 19:28) [Debbie Con] fix: corregi cita\n 1 file changed, 1 insertion(+), 1 deletion(-)\n\n23bac8f (2024-09-04, 19:27) [Aaron Retana] fix: arregla conflicto\nd43f101 (2024-09-04, 19:21) [Aaron Retana] feat: agrega primera parte del resumen\n 1 file changed, 273 insertions(+), 100 deletions(-)\n\n9b9c706 (2024-09-04, 19:20) [Andrey Prado] fix: Arregle Cambios\n5def0cd (2024-09-04, 19:16) [Debbie Con] feat: añadi prregunta investigacion y subtitulo\n 1 file changed, 5 insertions(+), 1 deletion(-)\n\n50fdb9b (2024-09-04, 18:59) [Andrey Prado] fix: Corrección Formato\n 1 file changed, 5 insertions(+)\n\nb8ba762 (2024-09-04, 18:19) [Andrey Prado] feat: añade referencias base de datos\n 1 file changed, 17 insertions(+)\n\n234e7e5 (2024-09-04, 18:14) [Andrey Prado] fix: Arreglé error references.bib\n 1 file changed, 2 insertions(+), 2 deletions(-)\n\nf824254 (2024-09-04, 18:10) [Debbie Con] feat: añadi citas en fichas\n 1 file changed, 5 insertions(+), 4 deletions(-)\n\n11ead08 (2024-09-04, 18:09) [Debbie Con] feat: añadi referencias\n 1 file changed, 12 insertions(+), 3 deletions(-)\n\nc589b3f (2024-09-04, 17:32) [Debbie Con] feat: añadi ficha 3\n 1 file changed, 15 insertions(+), 12 deletions(-)\n\na763be7 (2024-09-04, 17:28) [Andrey Prado] feat: Añadi Datos\n 1 file changed, 85 insertions(+), 5 deletions(-)\n\n29ab382 (2024-09-04, 17:15) [Andrey Prado] feat: Añadi parte datos\n 1 file changed, 8 insertions(+), 5 deletions(-)\n\n6183a7d (2024-09-04, 17:04) [Andrey Prado] feat: Agrega Bibliografía\n 1 file changed, 10 insertions(+)\n\n07a7b6e (2024-09-04, 16:53) [Debbie Con] feat: añadi segunda teoria\n 1 file changed, 5 insertions(+), 2 deletions(-)\n\ne08c51b (2024-09-04, 16:50) [Debbie Con] feat: añadi primera teoria\n 1 file changed, 3 insertions(+), 1 deletion(-)\n\ndf1bd2f (2024-09-04, 14:49) [Aaron Retana] chore: actualiza el sitio web posterior a nuevo render\n 2 files changed, 32 insertions(+), 53 deletions(-)\n\n7b7eadc (2024-09-04, 14:42) [Aaron Retana] chore: actualiza el sitio web\n 2 files changed, 62 insertions(+), 65 deletions(-)\n\n577e8b6 (2024-09-04, 14:36) [Aaron Retana] feat: añade las conclusiones de la argumentación de cada pregunta\n 1 file changed, 47 insertions(+), 3 deletions(-)\n\n4a5250b (2024-09-04, 14:21) [Aaron Retana] feat: agrega argumentos de la segunda pregunta\n 1 file changed, 20 insertions(+), 3 deletions(-)\n\n087d2eb (2024-09-04, 14:00) [Aaron Retana] feat: agrega ficha de literatura 2\n 1 file changed, 47 insertions(+), 34 deletions(-)\n\nb2ed73e (2024-09-04, 13:48) [Aaron Retana] feat: agrega ficha de literatura 1\n 1 file changed, 69 insertions(+), 16 deletions(-)\n\n96b5875 (2024-09-04, 12:02) [Aaron Retana] feat: incorpora argumentos de la cuarta pregunta\n 1 file changed, 23 insertions(+), 4 deletions(-)\n\ncfe8ed2 (2024-09-04, 11:54) [Aaron Retana] feat: agrega contraargumentos de cuarta pregunta\n 1 file changed, 21 insertions(+), 4 deletions(-)\n\n2a4d1d4 (2024-09-04, 11:44) [Aaron Retana] feat: añade argumentos de tercera pregunta\n 1 file changed, 20 insertions(+), 3 deletions(-)\n\nbf375c9 (2024-09-04, 11:36) [Aaron Retana] feat: añade contraargumentos de tercera pregunta\n 1 file changed, 20 insertions(+), 3 deletions(-)\n\n1e94c61 (2024-09-04, 11:31) [Aaron Retana] feat: agrega contraargumentos de segunda pregunta\n 1 file changed, 33 insertions(+), 6 deletions(-)\n\n2f4aba4 (2024-09-04, 11:20) [Aaron Retana] feat: agrega argumentos de primera pregunta\n 3 files changed, 27 insertions(+), 7 deletions(-)\n\nd496660 (2024-09-04, 11:12) [Aaron Retana] feat: agrega contraargumentos de primera pregunta\n 3 files changed, 259 insertions(+), 173 deletions(-)\n\n3b8db84 (2024-09-04, 10:46) [Aaron Retana] feat: agrega imagen de la UVE al sitio\n 1 file changed, 0 insertions(+), 0 deletions(-)\n\nfc41f72 (2024-09-04, 10:39) [Aaron Retana] feat: actualiza el sitio web\n 3 files changed, 416 insertions(+), 31 deletions(-)\n\n32e7b55 (2024-09-04, 10:36) [Aaron Retana] chore: modifica gitignore para incluir docs\n 1 file changed, 3 deletions(-)\n\n2582eb7 (2024-09-04, 10:24) [Aaron Retana] fix: agrega source a repo-actions\n 1 file changed, 1 insertion(+), 1 deletion(-)\n\n77744a8 (2024-09-04, 10:04) [Aaron Retana] fix: corrección de enlace del repositorio\n 1 file changed, 2 insertions(+), 2 deletions(-)\n\ncbf261f (2024-09-04, 01:24) [Andrey Prado] feat: error en commits\nf619a5d (2024-09-04, 01:23) [Andrey Prado] chore: error\n 1 file changed, 1 deletion(-)\n\nf36fcb7 (2024-09-04, 01:23) [Andrey Prado] feat: Bibliografía Urie Bronfenbrenner\n 1 file changed, 12 insertions(+), 1 deletion(-)\n\nab46e9b (2024-09-04, 01:12) [Debbie Con] chore: eliminar chapter referencias\n 1 file changed, 1 deletion(-)\n\nacd3650 (2024-09-04, 01:07) [Andrey Prado] feat: errores en url referencias\n1c7d78b (2024-09-04, 01:06) [Andrey Prado] fix: errores en el url\n 1 file changed, 5 insertions(+), 4 deletions(-)\n\n135b070 (2024-09-04, 01:05) [Debbie Con] fix: formato conceptos\n 1 file changed, 4 insertions(+), 4 deletions(-)\n\n800cc0a (2024-09-04, 01:01) [Andrey Prado] fix: error bibliografía\n 1 file changed, 1 insertion(+), 1 deletion(-)\n\nedbb294 (2024-09-04, 01:00) [Andrey Prado] feat: arreglo bibliografía\nf871707 (2024-09-04, 00:59) [Andrey Prado] feat: bibliografía nueva\n 1 file changed, 31 insertions(+), 1 deletion(-)\n\nadaf5aa (2024-09-04, 00:57) [Debbie Con] fix: formato teorias o principios\n 1 file changed, 5 insertions(+), 4 deletions(-)\n\n42b76e3 (2024-09-04, 00:55) [Debbie Con] feat: añadi nombre y seccion de teorias\n 1 file changed, 6 insertions(+)\n\n47bfed5 (2024-09-04, 00:47) [Debbie Con] feat: tension 2 y 3\n 1 file changed, 4 insertions(+), 2 deletions(-)\n\n9dcab5e (2024-09-04, 00:45) [Debbie Con] feat: preguntas añadidas en seccion respectiva\n 1 file changed, 5 insertions(+), 5 deletions(-)\n\n9e702ff (2024-09-04, 00:37) [Andrey Prado] fix: arreglo cita factor_académico\n 2 files changed, 5 insertions(+), 4 deletions(-)\n\n399ce05 (2024-09-04, 00:33) [Andrey Prado] feat: merge\n2125f37 (2024-09-04, 00:32) [Andrey Prado] feat: Arreglos a bitácora\n 1 file changed, 1 insertion(+), 1 deletion(-)\n\nf564b0b (2024-09-04, 00:31) [Andrey Prado] feat: Arreglo\n 1 file changed, 1 insertion(+), 1 deletion(-)\n\n4db0ad6 (2024-09-04, 00:30) [Andrey Prado] feat: Bibliografía nueva\n 1 file changed, 27 insertions(+)\n\nbdf38b9 (2024-09-04, 00:29) [Debbie Con] feat: añadi las 4 preguntas\n 1 file changed, 4 insertions(+), 4 deletions(-)\n\n6fe2daa (2024-09-04, 00:25) [Debbie Con] feat: añadi una tension\n 1 file changed, 2 insertions(+), 1 deletion(-)\n\n7a787ee (2024-09-04, 00:23) [Debbie Con] feat: añadi conceptos\n 1 file changed, 7 insertions(+), 4 deletions(-)\n\naf1ccda (2024-09-04, 00:13) [Andrey Prado] feat: bibliografía nueva\nf1d5304 (2024-09-04, 00:11) [Andrey Prado] feat: bibliografía nueva\n 2 files changed, 26 insertions(+), 2 deletions(-)\n\nc23e758 (2024-09-03, 23:59) [Debbie Con] feat: añadi definicion de la idea\n 1 file changed, 1 insertion(+)\n\n3ab3ce6 (2024-09-03, 23:51) [Debbie Con] fix: mejoras formato (area fichas literatura)\n 1 file changed, 10 insertions(+), 12 deletions(-)\n\nf208022 (2024-09-03, 23:42) [Andrey Prado] feat: Intento de Arreglo de errores\n 2 files changed, 2 insertions(+), 2 deletions(-)\n\nbb0f466 (2024-09-03, 23:30) [Debbie Con] fix: coreccion nombre de seccion introduccion\n 1 file changed, 1 insertion(+), 1 deletion(-)\n\n4f01101 (2024-09-03, 23:29) [Debbie Con] fix: correccion formato titulos\n 1 file changed, 20 insertions(+), 18 deletions(-)\n\n9433bea (2024-09-03, 23:16) [Debbie Con] fix: correccion parentesis\n 1 file changed, 1 insertion(+), 1 deletion(-)\n\n51d8077 (2024-09-03, 23:14) [Andrey Prado] chore: Arreglar formato documento\n 1 file changed, 197 insertions(+)\n\n8cd21a1 (2024-09-03, 23:13) [Andrey Prado] fix: Eliminar Sección\n 1 file changed, 1 insertion(+), 3 deletions(-)\n\ne14b8ab (2024-09-03, 23:13) [Andrey Prado] chore: Carpeta para imágenes\n 1 file changed, 0 insertions(+), 0 deletions(-)\n\n750bdcc (2024-09-03, 22:29) [Andrey Prado] fix: Arreglar formato\n 1 file changed, 214 deletions(-)\n\n8a60fa7 (2024-09-02, 18:06) [Andrey Prado] fix: Cambio de Base de Datos\n 1 file changed, 43 insertions(+), 43 deletions(-)\n\nc2cbb6d (2024-09-02, 12:02) [Andrey Prado] fix: Arreglos al Quarto\n 1 file changed, 7 insertions(+), 2 deletions(-)\n\n2e38202 (2024-09-02, 11:59) [Debbie Con] fix: correcciones formato\n 1 file changed, 1 deletion(-)\n\n5c9f323 (2024-09-02, 10:23) [Debbie Con] fix: correcciones formato preguntas\n 1 file changed, 18 insertions(+), 12 deletions(-)\n\n98567eb (2024-09-02, 00:49) [Andrey Prado] chore: Formato e Introducción del Análisis de Datos\n 1 file changed, 9 insertions(+), 1 deletion(-)\n\n357e23c (2024-09-02, 00:45) [Andrey Prado] feat: Introducción al Análisis de Datos\n 1 file changed, 4 insertions(+)\n\ne93aa82 (2024-09-02, 00:33) [Andrey Prado] feat: Referencia y Ficha de Literatura\n 1 file changed, 34 insertions(+), 1 deletion(-)\n\n14f4c2e (2024-09-02, 00:18) [Andrey Prado] chore: Argumentación pregunta 2\n 1 file changed, 8 insertions(+), 7 deletions(-)\n\n96d57c1 (2024-09-02, 00:13) [Andrey Prado] fix: Error en Formato\n 1 file changed, 5 insertions(+), 4 deletions(-)\n\ndd8faf7 (2024-09-02, 00:11) [Andrey Prado] feat: Formato Reformulación Pregunta\n 1 file changed, 99 insertions(+)\n\nafd711f (2024-09-02, 00:07) [Andrey Prado] feat: Pregunta #2\n 1 file changed, 22 insertions(+)\n\n67d6dca (2024-09-01, 23:59) [Andrey Prado] feat: Agregué Tensiones\nb9451f1 (2024-09-01, 03:02) [Debbie Con] fix: tildes\n 1 file changed, 4 insertions(+), 4 deletions(-)\n\nc30600e (2024-09-01, 02:59) [Debbie Con] feat: molde para argumentacion de la pregunta\n 1 file changed, 23 insertions(+), 1 deletion(-)\n\nd98e42b (2024-09-01, 02:45) [Debbie Con] feat: algunas definiciones añadidas\n 1 file changed, 7 insertions(+)\n\n2c52f8b (2024-09-01, 02:33) [Debbie Con] (origin/debbie) feat: titulos añadidos\n 1 file changed, 8 insertions(+)\n\n90a2a08 (2024-09-01, 02:04) [Debbie Con] fix: borrar pruebas\n 1 file changed, 1 insertion(+), 2 deletions(-)\n\n6be7511 (2024-08-31, 01:32) [Andrey Prado] Commit No Debería Ser Permitido\n 1 file changed, 2 insertions(+)\n\nc84a0c6 (2024-08-30, 19:41) [Andrey Prado] Commit no Debería Ser Permitido V3\n 1 file changed, 1 insertion(+), 1 deletion(-)\n\n0f53685 (2024-08-30, 19:40) [Andrey Prado] Commit no Debería Ser Permitido V2\n 1 file changed, 2 insertions(+)\n\nb301163 (2024-08-30, 19:16) [Aaron Retana] fix: elimina carpeta doc duplicada\n 14 files changed, 5 insertions(+), 2728 deletions(-)\n\n4fefac0 (2024-08-30, 19:03) [Debbie Con] feat: borrar pruebas\n 1 file changed, 5 deletions(-)\n\n5f61216 (2024-08-30, 19:00) [Debbie Con] feat: agrega nombres\n 2 files changed, 3 insertions(+), 2 deletions(-)\n\n171aaa9 (2024-08-30, 18:56) [Debbie Con] feat: prueba\n 2 files changed, 10 insertions(+), 5 deletions(-)\n\n44711d5 (2024-08-30, 18:52) [Debbie Con] fix: coreccion error doc\n 14 files changed, 2729 insertions(+), 1 deletion(-)\n\na35c1cf (2024-08-31, 00:28) [Andrey Prado] Falso\n 1 file changed, 4 insertions(+)\n\n5b93829 (2024-08-29, 19:36) [Aaron Retana] feat: agrega archivo de referencias\n 1 file changed, 0 insertions(+), 0 deletions(-)\n\n2c7ba90 (2024-08-29, 19:34) [Aaron Retana] feat: agrega archivo del índice\n 1 file changed, 4 insertions(+)\n\n1ab445e (2024-08-29, 19:29) [Aaron Retana] chore: agrega archivo de formato de quarto\n 1 file changed, 32 insertions(+)\n\nbb53d22 (2024-08-29, 19:24) [Aaron Retana] fix: cambiar nombre de la carpeta a docs\n 19 files changed, 0 insertions(+), 0 deletions(-)\n\nfebabc8 (2024-08-29, 17:38) [Aaron Retana] chore: actualiza sitio\n 19 files changed, 6015 insertions(+)\n\n6974691 (2024-08-29, 16:48) [Aaron Retana] chore: agrega configuración de pre-commit\n 1 file changed, 10 insertions(+)\n\nb62a792 (2024-08-29, 16:46) [Aaron Retana] feat: agrega proyecto de R\n 1 file changed, 13 insertions(+)\n\nb9a752a (2024-08-29, 12:04) [Aaron Retana] feat: agrega documento\n 1 file changed, 3 insertions(+)\n\n89b3a76 (2024-08-29, 09:24) [Debbie Con Ortega] Initial commit\n 2 files changed, 50 insertions(+)\n\n# Git summary\nproject     : Bitacoras-Grupo-4-CA-0204-II-2024- \\\n\n repo age    : 9 weeks \\\n \n branch:     : main \\\n \n last active : 12 minutes ago \\\n active on   : 19 days \\\n commits     : 228 \\\n files       : 240 \\\n \n uncommitted : 10 \\\n authors     : \\\n    87\tDebbie Con         38.2% \\\n    81\tAndrey Prado       35.5% \\\n    59\tAaron Retana       25.9% \\\n     1\tDebbie Con Ortega  0.4% \\\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}